-- Generated by tools/build-help.js from docs/ingamehelp/enUS/. Edit those and run
-- `npm run help`; `npm run check:help` fails when this file and they disagree.
local _, addon = ...;
local L = addon.L;

L["HELP_CAST_OPTIONS_TITLE"] = "What do Cast Options do?"
L["HELP_CAST_OPTIONS_BODY"] = [==[
|cnBLUE_FONT_COLOR:Cast Options|r in an action's right-click menu sets what this action does on each kind of press.

The |cnBLUE_FONT_COLOR:Self Cast Key|r and |cnBLUE_FONT_COLOR:Focus Cast Key|r rows each take one of three settings:

- |cnBLUE_FONT_COLOR:Cast on yourself|r or |cnBLUE_FONT_COLOR:Cast on your focus|r sends the action to that unit while you hold the key. A new action is set to this.
- |cnBLUE_FONT_COLOR:Cast on the usual target|r keeps the action in that press and sends it where it would go with no key held.
- |cnBLUE_FONT_COLOR:Skip this action|r takes it out of that press, and the press goes to the next action on the key.

> If a self cast or focus cast works on every key but one, look for a binding on the two keys together, in the game's Keybindings or in Debind. Holding the key reaches an action only while that combination has nothing bound to it: with ALT as your Self Cast Key, anything bound to ALT-X runs when you press X with ALT held.

> The Self Cast Key and the Focus Cast Key are the game's own keys, under Options > Gameplay > Combat.

|cnBLUE_FONT_COLOR:Hover Cast|r is a row of the same shape for the unit you point at, holding |cnBLUE_FONT_COLOR:Cast on the unit you point at|r, |cnBLUE_FONT_COLOR:Cast on the usual target|r and |cnBLUE_FONT_COLOR:Off|r. A new action is set to |cnBLUE_FONT_COLOR:Off|r, which does not stop the action from running: pointing at a unit simply does not change where it goes.

|cnBLUE_FONT_COLOR:Off|r and |cnBLUE_FONT_COLOR:Cast on the usual target|r differ only in the turn this action takes. With |cnBLUE_FONT_COLOR:Off|r, it is tried after every action on the key whose |cnBLUE_FONT_COLOR:Hover Cast|r is set to something else; with |cnBLUE_FONT_COLOR:Cast on the usual target|r, it keeps its usual place among them. The order itself is in |cnGREEN_FONT_COLOR:|Hdebind:help:ordering|h[When a key holds more than one action]|h|r.

To keep an action from running at all while you point at a unit, give it a condition under |cnBLUE_FONT_COLOR:Units|r. Under the three |cnBLUE_FONT_COLOR:Hover Cast|r settings is a mode row that says which units count as pointed at. Both are in |cnGREEN_FONT_COLOR:|Hdebind:help:hover-cast|h[What is Hover Cast?]|h|r.

> When a unit is chosen under |cnBLUE_FONT_COLOR:Target|r in the same menu, every press that runs this action sends it to that unit, so |cnBLUE_FONT_COLOR:Cast on yourself|r and |cnBLUE_FONT_COLOR:Cast on the usual target|r come to the same cast. Which of a picked target, a held key and a pointed unit comes first is in |cnGREEN_FONT_COLOR:|Hdebind:help:targeting|h[Which unit is an action used on?]|h|r.

|cnBLUE_FONT_COLOR:Normal Cast|r covers the press with no key held, unless |cnBLUE_FONT_COLOR:Hover Cast|r takes that press for this action. Untick it and that press goes to the next action on the key.

> On the left or right mouse button with no modifier nothing set in these rows is read, because that action runs only on a unit frame: |cnGREEN_FONT_COLOR:|Hdebind:help:clicking-a-unit-frame|h[What happens when you click a unit frame?]|h|r.
]==]

L["HELP_CLICKING_A_UNIT_FRAME_TITLE"] = "What happens when you click a unit frame?"
L["HELP_CLICKING_A_UNIT_FRAME_BODY"] = [==[
An action on the left or right mouse button with no modifier runs only when you click a unit frame, so a click anywhere else still reaches the game. On a frame it goes to the unit you click, and nothing set under |cnBLUE_FONT_COLOR:Cast Options|r is read.

The Self Cast Key and the Focus Cast Key are not used on a unit frame click. Holding one of them there is an ordinary modified click, which runs whatever you bound to that combination, under its own |cnBLUE_FONT_COLOR:Cast Options|r.

What each row of |cnBLUE_FONT_COLOR:Cast Options|r does is in |cnGREEN_FONT_COLOR:|Hdebind:help:cast-options|h[What do Cast Options do?]|h|r.
]==]

L["HELP_CUSTOM_MACRO_TITLE"] = "Writing a Custom Macro"
L["HELP_CUSTOM_MACRO_BODY"] = [==[
Anything a macro in the game's own list holds, and two things it cannot: the units below, and your Switches.

Write a unit after @, where you would name any other unit.

|cnHIGHLIGHT_FONT_COLOR:/cast [@healer,exists,nodead][] Innervate|r

- |cnHIGHLIGHT_FONT_COLOR:@tank, @healer, @maintank, @mainassist.|r The member of your group who holds that role, only while exactly one member holds it. Debind's settings can leave you out of each.
- |cnHIGHLIGHT_FONT_COLOR:@custom1, @custom2.|r The unit you set with |cnBLUE_FONT_COLOR:Set Custom Target|r.
- |cnHIGHLIGHT_FONT_COLOR:@unitframe.|r The unit on a unit frame Debind works on that your cursor is over as you press the key.
- |cnHIGHLIGHT_FONT_COLOR:@@.|r The unit this press aims at: you while the Self Cast Key is held, your focus while the Focus Cast Key is held, and the unit you point at with |cnBLUE_FONT_COLOR:Hover Cast|r. With none of these it is your target.

A name with nobody behind it is a unit that does not exist, so exists is false for it. Target and pet can follow any of these names, as in |cnHIGHLIGHT_FONT_COLOR:@tanktarget|r or |cnHIGHLIGHT_FONT_COLOR:@@target|r.

@@ always puts a unit in, so with nothing aimed at and no target nothing happens. Put a conditional on that part and an empty part after it, and the cast goes where it normally would.

|cnHIGHLIGHT_FONT_COLOR:/cast [@@,help][] Regrowth|r

A Switch works as a conditional too: |cnHIGHLIGHT_FONT_COLOR:[$fishing]|r while it is on, |cnHIGHLIGHT_FONT_COLOR:[no$fishing]|r while it is off. Use the name from |cnBLUE_FONT_COLOR:Switches|r.

Write these names in lower case and inside the brackets that open a part of a line, a unit straight after @ and a Switch straight after $. Written any other way they are left as plain text. Write |cnHIGHLIGHT_FONT_COLOR:[@tank]|r and not |cnHIGHLIGHT_FONT_COLOR:[target=tank]|r.
]==]

L["HELP_CUSTOM_TARGET_TITLE"] = "What is a Custom Target?"
L["HELP_CUSTOM_TARGET_BODY"] = [==[
Two extra targets you keep the way you keep your focus. Put |cnBLUE_FONT_COLOR:Set Custom Target 1|r or |cnBLUE_FONT_COLOR:Set Custom Target 2|r on a key, from the |cnBLUE_FONT_COLOR:Special|r tab of |cnBLUE_FONT_COLOR:Add an Action|r, then press that key with your cursor over a unit frame. Press it with your cursor over nothing to clear it.

Then use one like any other unit: pick |cnBLUE_FONT_COLOR:Custom Target 1|r or |cnBLUE_FONT_COLOR:Custom Target 2|r in an action's |cnBLUE_FONT_COLOR:Target|r menu, ask about it under |cnBLUE_FONT_COLOR:Units|r, or write |cnHIGHLIGHT_FONT_COLOR:@custom1|r or |cnHIGHLIGHT_FONT_COLOR:@custom2|r in a |cnBLUE_FONT_COLOR:Custom Macro|r, as in |cnGREEN_FONT_COLOR:|Hdebind:help:custom-macro|h[Writing a Custom Macro]|h|r.

You can set yourself, your pet, somebody in your party or raid, an encounter boss, or an arena opponent. On anything else the press does nothing and a line in chat says why. Each character has its own two, and they are still there at the next login.

Out of combat this works over any unit frame. In combat it works over the Player, Pet, Party, Raid, Boss and Arena frames Debind works on.

A custom target on somebody in your party or raid follows that person, even when the group changes. A boss or an arena opponent is the position rather than the person, so next time it is whoever stands there.

The exception is a party or raid custom target you set during a fight your group has already changed in. That one clears if the group changes again before the fight ends, and the line you get when you set it says so.
]==]

L["HELP_HOVER_CAST_TITLE"] = "What is Hover Cast?"
L["HELP_HOVER_CAST_BODY"] = [==[
|cnBLUE_FONT_COLOR:Hover Cast|r sends an action to the unit you point at instead of the usual target. You set it on each action: open |cnBLUE_FONT_COLOR:Cast Options|r in its right-click menu, then |cnBLUE_FONT_COLOR:Hover Cast|r, and pick |cnBLUE_FONT_COLOR:Cast on the unit you point at|r. A new action is set to |cnBLUE_FONT_COLOR:Off|r.

> An action with a unit picked under |cnBLUE_FONT_COLOR:Target|r goes to that unit whether you point at something or not.

Which units count as pointed at is a mode:

- |cnBLUE_FONT_COLOR:Unit Frames|r, the unit on a unit frame Debind works on, the game's own or a unit frame addon's. Away from one, nothing is pointed at.
- |cnBLUE_FONT_COLOR:Mouseover|r, a unit frame, a nameplate, or the unit itself in the world.

> |cnBLUE_FONT_COLOR:Unit Frame Support|r in Debind's settings lists the frames Debind works on. Every one counts until you take it out.

One mode on the settings tab covers the whole account. The same two are also on an action's own |cnBLUE_FONT_COLOR:Hover Cast|r row. Pick one there and that action uses it instead of the account's; until you do, the row is set to |cnBLUE_FONT_COLOR:Use the mode in Debind's settings|r.

|cnBLUE_FONT_COLOR:Off|r does not keep an action from running while you point at a unit: it runs with the target it would have anyway. To stop it there, put a condition on the unit you point at. Under |cnBLUE_FONT_COLOR:Units|r, pick |cnBLUE_FONT_COLOR:Unit Frame|r (or |cnBLUE_FONT_COLOR:Mouseover|r) and choose |cnBLUE_FONT_COLOR:When the unit doesn't exist|r.

The other rows of |cnBLUE_FONT_COLOR:Cast Options|r are in |cnGREEN_FONT_COLOR:|Hdebind:help:cast-options|h[What do Cast Options do?]|h|r. Which of a picked target, a held key and the unit you point at comes first is in |cnGREEN_FONT_COLOR:|Hdebind:help:targeting|h[Which unit is an action used on?]|h|r.
]==]

L["HELP_ORDERING_TITLE"] = "When a key holds more than one action"
L["HELP_ORDERING_BODY"] = [==[
Press a key that holds more than one action and Debind runs the first one whose conditions are met. If no action's conditions are met, the key does nothing: Debind keeps the key, and what WoW has bound to it does not run.

The |cnBLUE_FONT_COLOR:Overview|r tab lists actions grouped by key, and under one key they stand in the order they are tried. Three things put them in that order, and the first of the three where two actions differ settles which stands higher.

1. |cnHIGHLIGHT_FONT_COLOR:Importance, where the other two cannot do it.|r A higher |cnBLUE_FONT_COLOR:Importance|r stands above the rest whatever they say. It is set on the action, and an Account action is the same action on every character, so the order you give it here is the order it has on characters you are not playing and cannot see.
2. |cnHIGHLIGHT_FONT_COLOR:The layer it is in.|r |cnBLUE_FONT_COLOR:Move to...|r moves it between them, and the narrower layer stands higher, from this character and specialization down to Account.
3. |cnHIGHLIGHT_FONT_COLOR:Where you put it in that layer.|r |cnBLUE_FONT_COLOR:Run Sooner|r and |cnBLUE_FONT_COLOR:Run Later|r move the action one place. They are greyed out when one of the two above already settles the order, and the tooltip says which one.

Putting a condition on an action does not move it.

> |cnBLUE_FONT_COLOR:Use the old run order|r in Debind's settings adds a fourth test above the layer, for the whole account: an action with conditions is tried before one without. It is there for keys you set up under an earlier version, and it will be removed in a later version.

An action with no conditions is tried on every press, so nothing below it is ever reached. Give each one the conditions for the case it is meant for, and a press that meets none of them moves on to the next action down.

The last action on a key is the one to leave without conditions, so that it is tried when nothing above it ran. To reach the action bar slot that key used to press, pick that last one from the |cnBLUE_FONT_COLOR:Commands|r tab of |cnBLUE_FONT_COLOR:Add an Action|r, where the action bar buttons are listed.

Some of the |cnBLUE_FONT_COLOR:Cast Options|r change which of a key's actions are tried, and in what order. While you hold the Self Cast Key or the Focus Cast Key, only the actions set to use that key are tried, and if none of their conditions are met the key does nothing. While |cnBLUE_FONT_COLOR:Hover Cast|r has a unit under your cursor, the actions set to use it are tried first and the rest after them. You set these per action, and |cnGREEN_FONT_COLOR:|Hdebind:help:targeting|h[Which unit is an action used on?]|h|r explains them.

> Debind gives a key back when nothing on it is in play: every action either turned off in its own menu, or sitting in a specialization tab you are not in. WoW's own binding works there again, and the key's header is grey in the |cnBLUE_FONT_COLOR:Overview|r tab.
]==]

L["HELP_SETTING_KEYS_UP_TITLE"] = "How do I set my keys up?"
L["HELP_SETTING_KEYS_UP_BODY"] = [==[
# Where an action goes

Put an action in the layer that covers the most characters, and use a narrower layer only where a class or a specialization should run something else. A key in a narrower layer beats the same key in a broader one.

A mount every character uses sits in |cnBLUE_FONT_COLOR:Account|r / |cnBLUE_FONT_COLOR:General|r. Travel form sits in the druid layer, and a character who rides something else keeps that in its own.

Picking an entry in |cnBLUE_FONT_COLOR:Add an Action|r puts the new action in the layer you have open, and right-clicking the entry instead offers |cnBLUE_FONT_COLOR:Add to...|r, which lists every layer. |cnBLUE_FONT_COLOR:Move to...|r in an action's right-click menu moves one you already have.

You do not have to bind everything at once.

# Assigning a key, and everything else

Right-clicking an action sets everything about it, its key included, in either list on the |cnBLUE_FONT_COLOR:Overview|r tab. |cnBLUE_FONT_COLOR:Assign a key|r is the item that gives it one.

Left-click picks an action, and shift-click or control-click picks more than one, after which the menu writes to all of them. The |cnBLUE_FONT_COLOR:Overview|r tab also gathers each key's actions from every layer into one group, and clicking a key's heading picks everything under it, ready for that same menu.

# Conditions all have to be true

Give each action only the conditions it needs. Everything you pick under |cnBLUE_FONT_COLOR:Conditions|r has to be true at once, so an action that should run in two different situations is two actions.

# One key for a friend and an enemy

Both actions go on the same key. Which one is reached first is in |cnGREEN_FONT_COLOR:|Hdebind:help:ordering|h[When a key holds more than one action]|h|r. The harmful one goes above, carrying |cnBLUE_FONT_COLOR:Resolved Unit|r under |cnBLUE_FONT_COLOR:Conditions|r with |cnBLUE_FONT_COLOR:Enemy|r ticked, and the helpful one below it with no |cnBLUE_FONT_COLOR:Resolved Unit|r condition at all. The press then attacks an enemy and heals a friend. With nothing targeted the game places the cast, which is how Auto Self Cast puts a helpful spell on you.

# You may not need a Custom Macro

Conditions and a few actions on one key cover most of what a macro would, and the one above is an example. Writing one for what they leave out is in |cnGREEN_FONT_COLOR:|Hdebind:help:custom-macro|h[Writing a Custom Macro]|h|r.
]==]

L["HELP_SWITCHES_TITLE"] = "What are Switches for?"
L["HELP_SWITCHES_BODY"] = [==[
A Switch is a value of your own, either on or off. Put it on an action as a condition and that action runs only while the Switch is on, leaving the key to the next action while it is off, or to nothing at all. Make one with |cnBLUE_FONT_COLOR:New Switch|r on the |cnBLUE_FONT_COLOR:Switches|r tab, or with |cnBLUE_FONT_COLOR:Switches|r in an action's right-click menu, which makes it and puts it on that action in one step.

A Switch is read as a condition in two places: |cnBLUE_FONT_COLOR:Switches|r in an action's right-click menu, where you pick on or off, and a Custom Macro, where you write |cnHIGHLIGHT_FONT_COLOR:[$fishing]|r for on and |cnHIGHLIGHT_FONT_COLOR:[no$fishing]|r for off.

To change one with a key, add a |cnBLUE_FONT_COLOR:Switch|r action to that key from the |cnBLUE_FONT_COLOR:Special|r tab of |cnBLUE_FONT_COLOR:Add an Action|r, then pick in its menu which Switch it changes and whether the press turns that Switch on, turns it off, or flips it. A key does this in combat as well. The button on the Switch's own row, labelled |cnBLUE_FONT_COLOR:Turn On|r or |cnBLUE_FONT_COLOR:Turn Off|r by what a click will do, flips it, but not in combat.

|cnBLUE_FONT_COLOR:Starts as|r on the |cnBLUE_FONT_COLOR:Switches|r tab sets the value a Switch has after you log in and after you change specialization: |cnBLUE_FONT_COLOR:On|r, |cnBLUE_FONT_COLOR:Off|r, or |cnBLUE_FONT_COLOR:As you left it|r. |cnBLUE_FONT_COLOR:Set it for|r above it picks what that answer covers: the whole account, one class, one specialization or one character. The narrowest one that fits the character you are on is the one being read, and that one is blue in the list. Set it for one character and only that character starts with the Switch off, while the same action on the same key is untouched everywhere else.

Everything you pick in the condition menu has to be true at once, and some things have no row there at all. |cnBLUE_FONT_COLOR:Set automatically|r answers both: it takes a macro conditional, and the Switch is on exactly while that is true. |cnHIGHLIGHT_FONT_COLOR:[pet:Felhunter][pet:Voidwalker]|r is on while either of those two is out. One set this way cannot be flipped by hand or by a key.
]==]

L["HELP_TARGETING_TITLE"] = "Which unit is an action used on?"
L["HELP_TARGETING_BODY"] = [==[
Where an action goes is settled in this order, and the first that applies decides:

1. |cnHIGHLIGHT_FONT_COLOR:The target you picked|r under |cnBLUE_FONT_COLOR:Target|r. Nothing you hold or point at moves it. While that unit is not there the press stops with this action, and no other action on the key is tried; to pass it on, add |cnBLUE_FONT_COLOR:When the unit exists|r for that unit under |cnBLUE_FONT_COLOR:Units|r.
2. |cnHIGHLIGHT_FONT_COLOR:The key you hold.|r The Self Cast Key sends the action to you and the Focus Cast Key to your focus. With no focus set, the press does nothing. A key turned off in Debind's settings counts as not held.
3. |cnHIGHLIGHT_FONT_COLOR:The unit you point at.|r Which units count is the |cnBLUE_FONT_COLOR:Hover Cast|r mode in Debind's settings. The game's own Mouseover Cast does not apply to Debind keys.
4. |cnHIGHLIGHT_FONT_COLOR:None of these.|r The game places the cast as it does on an action bar.

|cnBLUE_FONT_COLOR:Unit Frame|r under |cnBLUE_FONT_COLOR:Target|r is narrower than |cnBLUE_FONT_COLOR:Mouseover|r: only the unit on a unit frame Debind works on, whether that frame belongs to the game or to a unit frame addon. Which frames those are is set in Debind's settings.

Auto Self Cast is the game's own, and a Debind key goes out with it as an action bar button does. The |cnBLUE_FONT_COLOR:Auto Self Cast|r row under |cnBLUE_FONT_COLOR:Cast Options|r sets it for one action.

The game's own settings look at the unit under your cursor before the key you hold. Debind does it the other way round.

The |cnBLUE_FONT_COLOR:Resolved Unit|r condition under |cnBLUE_FONT_COLOR:Units|r asks about the unit this order arrives at. Debind does not check whether a spell suits that unit, so when it matters, put a condition there.

How each action answers a held key or a pointed unit is set under |cnBLUE_FONT_COLOR:Cast Options|r in its right-click menu, explained in |cnGREEN_FONT_COLOR:|Hdebind:help:cast-options|h[What do Cast Options do?]|h|r.
]==]
