-- Generated by tools/build-help.js from docs/ingamehelp/enUS/. Edit those and run
-- `npm run help`; `npm run check:help` fails when this file and they disagree.
local _, addon = ...;
local L = addon.L;

L["HELP_CAST_OPTIONS_TITLE"] = "What do the Cast Options do?"
L["HELP_CAST_OPTIONS_BODY"] = [==[
|cnBLUE_FONT_COLOR:Cast Options|r in an action's right-click menu says what the action does on each kind of press. The Self Cast Key, Focus Cast Key and |cnBLUE_FONT_COLOR:Hover Cast|r rows each take one of three answers:

- |cnBLUE_FONT_COLOR:Cast on yourself|r, |cnBLUE_FONT_COLOR:Cast on your focus|r or |cnBLUE_FONT_COLOR:Cast on the unit you point at|r sends the action to that unit. The two key rows do this unless you change them; |cnBLUE_FONT_COLOR:Hover Cast|r starts off, so pointing at a unit does nothing until you turn it on.
- |cnBLUE_FONT_COLOR:Cast as usual|r keeps the action's place on the key and sends it where it would go with nothing held or pointed at.
- |cnBLUE_FONT_COLOR:Off|r makes no binding for that press. On the two key rows the action is out of that press and the next action on the key takes it. On |cnBLUE_FONT_COLOR:Hover Cast|r the action still runs, behind every action on the key that does answer a pointed press.

To keep an action from running while you point at a unit, put a condition on that unit instead: under |cnBLUE_FONT_COLOR:Units|r, pick |cnBLUE_FONT_COLOR:Unit Frame|r (or |cnBLUE_FONT_COLOR:Mouseover|r) and choose |cnBLUE_FONT_COLOR:When the unit doesn't exist|r.

When a unit is chosen under |cnBLUE_FONT_COLOR:Target|r, the first answer on each row sends the action to that unit instead, and |cnBLUE_FONT_COLOR:Cast as usual|r is locked. Which of the target, a held key and a pointed unit comes first is in |cnGREEN_FONT_COLOR:|Hdebind:help:targeting|h[Which unit is an action used on?]|h|r.

|cnBLUE_FONT_COLOR:Hover Cast|r also says which units count as pointed at for this action: |cnBLUE_FONT_COLOR:Use the mode in Debind's settings|r, or |cnBLUE_FONT_COLOR:Unit Frames|r or |cnBLUE_FONT_COLOR:Mouseover|r for this action alone.

|cnBLUE_FONT_COLOR:Normal Cast|r is the press with nothing held and nothing pointed at. Untick it and the action runs only on a held key or a pointed unit, and that plain press goes to the next action on the key.

Clicking a unit frame does not use the Self Cast Key or the Focus Cast Key. A key held on the click picks the binding you made for that exact combination, so the click still goes to the frame's unit.

An action on the left or right mouse button with no modifier runs only when you click a unit frame. There it ignores |cnBLUE_FONT_COLOR:Normal Cast|r and |cnBLUE_FONT_COLOR:Hover Cast|r, using |cnBLUE_FONT_COLOR:Unit Frames|r and the unit you click, so a click anywhere else still reaches the game.
]==]

L["HELP_CUSTOM_MACRO_TITLE"] = "Which extra units can a Custom Macro aim at?"
L["HELP_CUSTOM_MACRO_BODY"] = [==[
A |cnBLUE_FONT_COLOR:Custom Macro|r can aim at these units, which a macro in the game's own list cannot. Write them like any other unit, as in /cast [@tank,exists] Rejuvenation; Regrowth.

- |cnHIGHLIGHT_FONT_COLOR:@tank, @healer, @maintank, @mainassist.|r The member of your group who holds that role, only while exactly one member holds it. Debind's settings can leave you out of each.
- |cnHIGHLIGHT_FONT_COLOR:@custom1, @custom2.|r The unit you pinned with |cnBLUE_FONT_COLOR:Set Custom Target|r.
- |cnHIGHLIGHT_FONT_COLOR:@unitframe.|r The unit on the unit frame you press the key over.
- |cnHIGHLIGHT_FONT_COLOR:@@.|r The unit this press aims at: you while the Self Cast Key is held, your focus while the Focus Cast Key is held, and the unit you point at with |cnBLUE_FONT_COLOR:Hover Cast|r. With none of these it is as if it were not written.

A unit nobody holds counts as not existing, so add exists to go on to the next part of the line. Target and pet can follow a name, as in @tanktarget, except after @@.

Write them in lower case, with @, in the brackets that open each part of a line. Anywhere else they are left as plain text.
]==]

L["HELP_HOVER_CAST_TITLE"] = "What is Hover Cast?"
L["HELP_HOVER_CAST_BODY"] = [==[
While you point at a unit, a key sends its action to that unit instead of where it would normally go. Point at nothing and the action goes where it normally would, and an action with a target picked under |cnBLUE_FONT_COLOR:Target|r keeps going there.

|cnHIGHLIGHT_FONT_COLOR:It is off on each action until you turn it on|r, in the action's right-click menu under |cnBLUE_FONT_COLOR:Cast Options|r. You can turn it on for several actions at once. The same menu lets one action use a mode of its own.

Which units count as pointed at is the mode in Debind's settings:

- |cnBLUE_FONT_COLOR:Unit Frames|r, the unit of the unit frame under your cursor. Away from a unit frame nothing is pointed at.
- |cnBLUE_FONT_COLOR:Mouseover|r, a unit frame, a nameplate, or the unit itself in the world.

The unit is handed to the action, and what the action can do with it is the action's own business: a macro or a mount takes no unit and runs the way it always does. It is used as it is, too. Debind does not ask whether the spell is friendly or harmful, so an attack aimed at a party member goes nowhere. Put a condition on the action when that matters.

What each row of |cnBLUE_FONT_COLOR:Cast Options|r does, and how to keep an action from running while you point at a unit, is in |cnGREEN_FONT_COLOR:|Hdebind:help:cast-options|h[What do the Cast Options do?]|h|r. Which of a picked target, a held key and a pointed unit comes first is in |cnGREEN_FONT_COLOR:|Hdebind:help:targeting|h[Which unit is an action used on?]|h|r.
]==]

L["HELP_ORDERING_TITLE"] = "Which action does a key run?"
L["HELP_ORDERING_BODY"] = [==[
A key can hold more than one action. Press it and Debind runs the first one whose conditions are met. If none of them does, the key does nothing.

The order is the one under the key in the list on the left of the |cnBLUE_FONT_COLOR:Overview|r tab, where actions are grouped by key. It is decided by these, from the top. The first one where two actions differ settles it.

1. |cnBLUE_FONT_COLOR:Importance|r. The higher one goes first.
2. |cnBLUE_FONT_COLOR:Conditions|r. An action with conditions goes before one without.
3. |cnHIGHLIGHT_FONT_COLOR:Layer.|r The narrower layer goes first, from this character and specialization down to Account. Set with |cnBLUE_FONT_COLOR:Move to...|r.
4. |cnHIGHLIGHT_FONT_COLOR:Position.|r When all three are equal, |cnBLUE_FONT_COLOR:Run Sooner|r and |cnBLUE_FONT_COLOR:Run Later|r move the action one place. They are greyed out when one of the three above already decides, and the tooltip says which.

While you hold the Self Cast Key or the Focus Cast Key, unless it is turned off in Debind's settings, only the actions that answer that key are tried. While you point at a unit, the actions that answer that are tried first, and the rest after them. What each action answers is set under |cnBLUE_FONT_COLOR:Cast Options|r, explained in |cnGREEN_FONT_COLOR:|Hdebind:help:targeting|h[Which unit is an action used on?]|h|r.
]==]

L["HELP_PICKING_A_POINTED_UNIT_TITLE"] = "What if the target is Unit Frame or Mouseover?"
L["HELP_PICKING_A_POINTED_UNIT_BODY"] = [==[
The action goes only to that unit. While you point at nothing there is no such unit, and the press does nothing, the way an action aimed at your focus does with no focus set.

To hand the press to the next action instead, give the action |cnBLUE_FONT_COLOR:When the unit exists|r on that unit under |cnBLUE_FONT_COLOR:Units|r.
]==]

L["HELP_STOPPING_AN_ACTION_TITLE"] = "How do I stop an action from running?"
L["HELP_STOPPING_AN_ACTION_BODY"] = [==[
|cnHIGHLIGHT_FONT_COLOR:Turn it off.|r |cnBLUE_FONT_COLOR:Turn this action off|r in its right-click menu stops the action. The key goes to the next action on it, and when every action on it is off, back to whatever WoW has bound to it. It keeps everything you set on it, so turning it back on puts it where it was.

|cnHIGHLIGHT_FONT_COLOR:Cover it.|r Put an action above it on the same key with a condition for the case you want stopped. The one above runs in that case and the one below never gets the press. When you want nothing to happen there, give the action above the type |cnBLUE_FONT_COLOR:Nothing|r.

|cnHIGHLIGHT_FONT_COLOR:Delete it.|r |cnBLUE_FONT_COLOR:Delete|r takes the action and everything set on it: the conditions, the importance and its place in the key.

To stop an action on one kind of press only, use |cnBLUE_FONT_COLOR:Cast Options|r instead: |cnGREEN_FONT_COLOR:|Hdebind:help:cast-options|h[What do the Cast Options do?]|h|r.
]==]

L["HELP_TARGETING_TITLE"] = "Which unit is an action used on?"
L["HELP_TARGETING_BODY"] = [==[
Where an action goes is settled in this order, and the first that applies decides:

1. |cnHIGHLIGHT_FONT_COLOR:The target you picked|r under |cnBLUE_FONT_COLOR:Target|r. Nothing you hold or point at moves it. If it is |cnBLUE_FONT_COLOR:Unit Frame|r or |cnBLUE_FONT_COLOR:Mouseover|r, read |cnGREEN_FONT_COLOR:|Hdebind:help:picking-a-pointed-unit|h[What if the target is Unit Frame or Mouseover?]|h|r.
2. |cnHIGHLIGHT_FONT_COLOR:The key you hold.|r The Self Cast Key sends the action to you and the Focus Cast Key to your focus. With no focus set, the press does nothing. A key turned off in Debind's settings counts as not held.
3. |cnHIGHLIGHT_FONT_COLOR:The unit you point at.|r Which units count is the |cnBLUE_FONT_COLOR:Hover Cast|r mode in Debind's settings. The game's own Mouseover Cast does not apply to Debind keys.
4. |cnHIGHLIGHT_FONT_COLOR:None of these.|r The game places the cast as it does on an action bar. This is the only case Auto Self Cast applies.

The game's own settings look at the unit under your cursor before the key you hold. Debind does it the other way round.

The |cnBLUE_FONT_COLOR:Resolved Unit|r condition under |cnBLUE_FONT_COLOR:Units|r asks about the unit this order arrives at. Debind does not check whether a spell suits that unit, so when it matters, put a condition there.

How each action answers a held key or a pointed unit is set under |cnBLUE_FONT_COLOR:Cast Options|r in its right-click menu, explained in |cnGREEN_FONT_COLOR:|Hdebind:help:cast-options|h[What do the Cast Options do?]|h|r.
]==]
