// Writes `Debind/DevStamp.lua`, naming the checkout the game is currently loading.
//
// A released build has its version stamped into the TOC by the packager; a working copy does not,
// and this is what stands in for it. The file is gitignored and its TOC line lives inside
// `#@debug@`, so nothing here can reach a user.
//
// Run by `.git/hooks/post-checkout` (see `devdocs/dev-setup.md`), and safe to run by hand.
// Worktrees share the common `.git`, so one hook covers all of them -- and because the hook runs
// with the worktree as its working directory, each writes its own stamp.

const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

// **The root comes from the working directory, not from this file's location.** Worktrees share one
// `.git`, so they also share the hook -- and the hook runs a script that lives in whichever
// checkout installed it. Deriving the root from `__dirname` made every worktree stamp the same
// file, with the same branch name, which is the one thing this must not do.
function git(...args) {
    return execFileSync("git", args, { cwd: process.cwd(), encoding: "utf8" }).trim();
}

const repoRoot = git("rev-parse", "--show-toplevel");
const target = path.join(repoRoot, "Debind", "DevStamp.lua");

// A detached HEAD has no branch name, which is the normal state of a worktree checked out at a
// release tag -- exactly the case where knowing what is loaded matters most. Name the tag, or the
// short sha when there is no tag.
function describeCheckout() {
    const branch = git("rev-parse", "--abbrev-ref", "HEAD");
    if (branch !== "HEAD") {
        return branch;
    }
    try {
        return git("describe", "--tags", "--exact-match", "HEAD");
    } catch {
        return git("rev-parse", "--short", "HEAD");
    }
}

const label = describeCheckout();
const body = `-- Generated by tools/stamp-dev.js. Not tracked; edits here are overwritten.
local _, DebindPrivate = ...;
DebindPrivate.DEV_STAMP = ${JSON.stringify(label)};
`;

// Only write when it actually changed, so a checkout that did not move the branch does not touch
// the file's mtime and make the addon look edited.
if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== body) {
    fs.writeFileSync(target, body);
}

process.stdout.write(`${label}\n`);
