local _, DebindPrivate = ...;

--- **Generated by `tools/build-camelot-class-spells.js`. Do not edit by hand**: run the three
--- steps again (`tools/fetch-camelot-class-spells.js`). Built from the camelot probe's record of
--- 1.60.1.70124, 2026-10-01 17:32: wowhead's class lists, a pet's books and the professions' pages, as the
--- client answered them, without what it called passive or did not know.
---
--- `[first rank's id] = { level required, classes = }`, and `[higher rank's id] = first rank's id`.
--- A string in a level's place says where the spell comes from (`CompareUnlearnedValue`); no
--- `classes` is every class's. The first ranks are the spell list's unlearned rows
--- (`UnlearnedSpells_Camelot.lua`), and the id an action stores (`CanonicalSpellID`). Loaded on
--- that client only (`Debind.toc`).
local DRUID = { DRUID = true };
local HUNTER = { HUNTER = true };
local MAGE = { MAGE = true };
local PALADIN = { PALADIN = true };
local PRIEST = { PRIEST = true };
local ROGUE = { ROGUE = true };
local SHAMAN = { SHAMAN = true };
local WARLOCK = { WARLOCK = true };
local WARRIOR = { WARRIOR = true };

DebindPrivate.CamelotSpells = {
    [2259] = { "profession" }, -- Alchemy
    [3101] = 2259,
    [3464] = 2259,
    [11611] = 2259,
    [1240943] = 2259,
    [1240954] = 2259,
    [1240965] = 2259,
    [1240977] = 2259,
    [9788] = { "profession" }, -- Armorsmith
    [1278067] = { "profession" }, -- Bait and Tackle
    [2018] = { "profession" }, -- Blacksmithing
    [3100] = 2018,
    [3538] = 2018,
    [9785] = 2018,
    [1240944] = 2018,
    [1240955] = 2018,
    [1240966] = 2018,
    [1240979] = 2018,
    [2550] = { "profession" }, -- Cooking
    [3102] = 2550,
    [3413] = 2550,
    [18260] = 2550,
    [1240945] = 2550,
    [1240956] = 2550,
    [1240967] = 2550,
    [1240980] = 2550,
    [13262] = { "profession" }, -- Disenchant
    [10656] = { "profession" }, -- Dragonscale Leatherworking
    [10658] = { "profession" }, -- Elemental Leatherworking
    [7411] = { "profession" }, -- Enchanting
    [7412] = 7411,
    [7413] = 7411,
    [13920] = 7411,
    [1240946] = 7411,
    [1240957] = 7411,
    [1240968] = 7411,
    [1240981] = 7411,
    [4036] = { "profession" }, -- Engineering
    [4037] = 4036,
    [4038] = 4036,
    [12656] = 4036,
    [1240947] = 4036,
    [1240958] = 4036,
    [1240969] = 4036,
    [1240982] = 4036,
    [43308] = { "profession" }, -- Find Fish
    [2383] = { "profession" }, -- Find Herbs
    [2580] = { "profession" }, -- Find Minerals
    [3273] = { "profession" }, -- First Aid
    [3274] = 3273,
    [7924] = 3273,
    [10846] = 3273,
    [1240927] = 3273,
    [1240928] = 3273,
    [1240929] = 3273,
    [1240930] = 3273,
    [7620] = { "profession" }, -- Fishing
    [7731] = 7620,
    [7732] = 7620,
    [18248] = 7620,
    [1240948] = 7620,
    [1240959] = 7620,
    [1240970] = 7620,
    [1240983] = 7620,
    [1278062] = { "profession" }, -- Gardening
    [20219] = { "profession" }, -- Gnomish Engineer
    [20222] = { "profession" }, -- Goblin Engineer
    [2366] = { "profession" }, -- Herbalism
    [2368] = 2366,
    [3570] = 2366,
    [11993] = 2366,
    [1240949] = 2366,
    [1240960] = 2366,
    [1240971] = 2366,
    [1240984] = 2366,
    [2108] = { "profession" }, -- Leatherworking
    [3104] = 2108,
    [3811] = 2108,
    [10662] = 2108,
    [1240950] = 2108,
    [1240961] = 2108,
    [1240972] = 2108,
    [1240985] = 2108,
    [17041] = { "profession" }, -- Master Axesmith
    [17040] = { "profession" }, -- Master Hammersmith
    [17039] = { "profession" }, -- Master Swordsmith
    [2575] = { "profession" }, -- Mining
    [2576] = 2575,
    [3564] = 2575,
    [10248] = 2575,
    [1240951] = 2575,
    [1240962] = 2575,
    [1240973] = 2575,
    [1240986] = 2575,
    [8613] = { "profession" }, -- Skinning
    [8617] = 8613,
    [8618] = 8613,
    [10768] = 8613,
    [1240952] = 8613,
    [1240963] = 8613,
    [1240974] = 8613,
    [1240987] = 8613,
    [2656] = { "profession" }, -- Smelting
    [3908] = { "profession" }, -- Tailoring
    [3909] = 3908,
    [3910] = 3908,
    [12180] = 3908,
    [1240953] = 3908,
    [1240964] = 3908,
    [1240976] = 3908,
    [1240988] = 3908,
    [1278068] = { "profession" }, -- Tanning
    [10660] = { "profession" }, -- Tribal Leatherworking
    [9787] = { "profession" }, -- Weaponsmith
    [2893] = { 26, classes = DRUID }, -- Abolish Poison
    [1066] = { 16, classes = DRUID }, -- Aquatic Form
    [22812] = { 44, classes = DRUID }, -- Barkskin
    [5211] = { 14, classes = DRUID }, -- Bash
    [6798] = 5211,
    [8983] = 5211,
    [5487] = { 10, classes = DRUID }, -- Bear Form
    [768] = { 20, classes = DRUID }, -- Cat Form
    [5209] = { 28, classes = DRUID }, -- Challenging Roar
    [1082] = { 20, classes = DRUID }, -- Claw
    [3029] = 1082,
    [5201] = 1082,
    [9849] = 1082,
    [9850] = 1082,
    [8998] = { 28, classes = DRUID }, -- Cower
    [9000] = 8998,
    [9892] = 8998,
    [8946] = { 14, classes = DRUID }, -- Cure Poison
    [1850] = { 26, classes = DRUID }, -- Dash
    [9821] = 1850,
    [99] = { 10, classes = DRUID }, -- Demoralizing Roar
    [1735] = 99,
    [9490] = 99,
    [9747] = 99,
    [9898] = 99,
    [9634] = { 40, classes = DRUID }, -- Dire Bear Form
    [5229] = { 12, classes = DRUID }, -- Enrage
    [339] = { 8, classes = DRUID }, -- Entangling Roots
    [1062] = 339,
    [5195] = 339,
    [5196] = 339,
    [9852] = 339,
    [9853] = 339,
    [770] = { 18, classes = DRUID }, -- Faerie Fire
    [778] = 770,
    [9749] = 770,
    [9907] = 770,
    [16979] = { 20, classes = DRUID }, -- Feral Charge (Bear)
    [22568] = { 32, classes = DRUID }, -- Ferocious Bite
    [22827] = 22568,
    [22828] = 22568,
    [22829] = 22568,
    [31018] = 22568,
    [22842] = { 36, classes = DRUID }, -- Frenzied Regeneration
    [21849] = { 50, classes = DRUID }, -- Gift of the Wild
    [21850] = 21849,
    [6795] = { 10, classes = DRUID }, -- Growl
    [5185] = { 1, classes = DRUID }, -- Healing Touch
    [5186] = 5185,
    [5187] = 5185,
    [5188] = 5185,
    [5189] = 5185,
    [6778] = 5185,
    [8903] = 5185,
    [9758] = 5185,
    [9888] = 5185,
    [9889] = 5185,
    [25297] = 5185,
    [2637] = { 18, classes = DRUID }, -- Hibernate
    [18657] = 2637,
    [18658] = 2637,
    [16914] = { 40, classes = DRUID }, -- Hurricane
    [17401] = 16914,
    [17402] = 16914,
    [29166] = { 40, classes = DRUID }, -- Innervate
    [24974] = { 30, classes = DRUID }, -- Insect Swarm
    [24975] = 24974,
    [24976] = 24974,
    [24977] = 24974,
    [414644] = { 42, classes = DRUID }, -- Lacerate
    [1235826] = 414644,
    [1235827] = 414644,
    [1126] = { 1, classes = DRUID }, -- Mark of the Wild
    [5232] = 1126,
    [5234] = 1126,
    [6756] = 1126,
    [8907] = 1126,
    [9884] = 1126,
    [9885] = 1126,
    [6807] = { 10, classes = DRUID }, -- Maul
    [6808] = 6807,
    [6809] = 6807,
    [8972] = 6807,
    [9745] = 6807,
    [9880] = 6807,
    [9881] = 6807,
    [8921] = { 4, classes = DRUID }, -- Moonfire
    [8924] = 8921,
    [8925] = 8921,
    [8926] = 8921,
    [8927] = 8921,
    [8928] = 8921,
    [8929] = 8921,
    [9833] = 8921,
    [9834] = 8921,
    [9835] = 8921,
    [16689] = { 10, classes = DRUID }, -- Nature's Grasp
    [16810] = 16689,
    [16811] = 16689,
    [16812] = 16689,
    [16813] = 16689,
    [17329] = 16689,
    [9005] = { 36, classes = DRUID }, -- Pounce
    [9823] = 9005,
    [9827] = 9005,
    [1238069] = { 36, classes = DRUID }, -- Primal Bite
    [1238070] = 1238069,
    [1238073] = 1238069,
    [5215] = { 20, classes = DRUID }, -- Prowl
    [6783] = 5215,
    [9913] = 5215,
    [1822] = { 24, classes = DRUID }, -- Rake
    [1823] = 1822,
    [1824] = 1822,
    [9904] = 1822,
    [6785] = { 32, classes = DRUID }, -- Ravage
    [6787] = 6785,
    [9866] = 6785,
    [9867] = 6785,
    [20484] = { 20, classes = DRUID }, -- Rebirth
    [20739] = 20484,
    [20742] = 20484,
    [20747] = 20484,
    [20748] = 20484,
    [8936] = { 12, classes = DRUID }, -- Regrowth
    [8938] = 8936,
    [8939] = 8936,
    [8940] = 8936,
    [8941] = 8936,
    [9750] = 8936,
    [9856] = 8936,
    [9857] = 8936,
    [9858] = 8936,
    [774] = { 4, classes = DRUID }, -- Rejuvenation
    [1058] = 774,
    [1430] = 774,
    [2090] = 774,
    [2091] = 774,
    [3627] = 774,
    [8910] = 774,
    [9839] = 774,
    [9840] = 774,
    [9841] = 774,
    [25299] = 774,
    [2782] = { 24, classes = DRUID }, -- Remove Curse
    [437138] = { 12, classes = DRUID }, -- Revive
    [1237948] = 437138,
    [1237949] = 437138,
    [1237950] = 437138,
    [1237951] = 437138,
    [1079] = { 20, classes = DRUID }, -- Rip
    [9492] = 1079,
    [9493] = 1079,
    [9752] = 1079,
    [9894] = 1079,
    [9896] = 1079,
    [5221] = { 22, classes = DRUID }, -- Shred
    [6800] = 5221,
    [8992] = 5221,
    [9829] = 5221,
    [9830] = 5221,
    [2908] = { 22, classes = DRUID }, -- Soothe Animal
    [8955] = 2908,
    [9901] = 2908,
    [2912] = { 20, classes = DRUID }, -- Starfire
    [8949] = 2912,
    [8950] = 2912,
    [8951] = 2912,
    [9875] = 2912,
    [9876] = 2912,
    [25298] = 2912,
    [411128] = { 1, classes = DRUID }, -- Swipe
    [769] = 411128,
    [779] = 411128,
    [780] = 411128,
    [9754] = 411128,
    [9908] = 411128,
    [18960] = { 10, classes = DRUID }, -- Teleport: Moonglade
    [467] = { 6, classes = DRUID }, -- Thorns
    [782] = 467,
    [1075] = 467,
    [8914] = 467,
    [9756] = 467,
    [9910] = 467,
    [417045] = { 1, classes = DRUID }, -- Tiger's Fury
    [5217] = 417045,
    [5225] = { 32, classes = DRUID }, -- Track Humanoids
    [740] = { 30, classes = DRUID }, -- Tranquility
    [8918] = 740,
    [9862] = 740,
    [9863] = 740,
    [783] = { 30, classes = DRUID }, -- Travel Form
    [1238214] = { 50, classes = DRUID }, -- Wild Growth
    [1238215] = 1238214,
    [5176] = { 1, classes = DRUID }, -- Wrath
    [5177] = 5176,
    [5178] = 5176,
    [5179] = 5176,
    [5180] = 5176,
    [6780] = 5176,
    [8905] = 5176,
    [9912] = 5176,
    [19434] = { 20, classes = HUNTER }, -- Aimed Shot
    [20900] = 19434,
    [20901] = 19434,
    [20902] = 19434,
    [20903] = 19434,
    [20904] = 19434,
    [3044] = { 6, classes = HUNTER }, -- Arcane Shot
    [14281] = 3044,
    [14282] = 3044,
    [14283] = 3044,
    [14284] = 3044,
    [14285] = 3044,
    [14286] = 3044,
    [14287] = 3044,
    [13161] = { 30, classes = HUNTER }, -- Aspect of the Beast
    [1299445] = 13161,
    [1299446] = 13161,
    [1299447] = 13161,
    [5118] = { 20, classes = HUNTER }, -- Aspect of the Cheetah
    [13165] = { 10, classes = HUNTER }, -- Aspect of the Hawk
    [14318] = 13165,
    [14319] = 13165,
    [14320] = 13165,
    [14321] = 13165,
    [14322] = 13165,
    [25296] = 13165,
    [13163] = { 4, classes = HUNTER }, -- Aspect of the Monkey
    [13159] = { 40, classes = HUNTER }, -- Aspect of the Pack
    [20043] = { 46, classes = HUNTER }, -- Aspect of the Wild
    [20190] = 20043,
    [1462] = { 24, classes = HUNTER }, -- Beast Lore
    [17253] = { "pet", classes = HUNTER }, -- Bite
    [17255] = 17253,
    [17256] = 17253,
    [17257] = 17253,
    [17258] = 17253,
    [17259] = 17253,
    [17260] = 17253,
    [17261] = 17253,
    [883] = { 10, classes = HUNTER }, -- Call Pet
    [7371] = { "pet", classes = HUNTER }, -- Charge
    [26177] = 7371,
    [26178] = 7371,
    [26179] = 7371,
    [26201] = 7371,
    [27685] = 7371,
    [16827] = { "pet", classes = HUNTER }, -- Claw
    [3009] = 16827,
    [3010] = 16827,
    [16828] = 16827,
    [16829] = 16827,
    [16830] = 16827,
    [16831] = 16827,
    [16832] = 16827,
    [5116] = { 8, classes = HUNTER }, -- Concussive Shot
    [1242634] = { 30, classes = HUNTER }, -- Counterattack
    [20909] = 1242634,
    [20910] = 1242634,
    [1742] = { "pet", classes = HUNTER }, -- Cower
    [1753] = 1742,
    [1754] = 1742,
    [1755] = 1742,
    [1756] = 1742,
    [16697] = 1742,
    [23099] = { "pet", classes = HUNTER }, -- Dash
    [23109] = 23099,
    [23110] = 23099,
    [24423] = { "pet", classes = HUNTER }, -- Demoralizing Screech
    [24577] = 24423,
    [24578] = 24423,
    [24579] = 24423,
    [781] = { 20, classes = HUNTER }, -- Disengage
    [14272] = 781,
    [14273] = 781,
    [1264758] = { "pet", classes = HUNTER }, -- Dismember
    [1264927] = 1264758,
    [1264929] = 1264758,
    [1264930] = 1264758,
    [1264933] = 1264758,
    [2641] = { 10, classes = HUNTER }, -- Dismiss Pet
    [20736] = { 12, classes = HUNTER }, -- Distracting Shot
    [14274] = 20736,
    [15629] = 20736,
    [15630] = 20736,
    [15631] = 20736,
    [15632] = 20736,
    [23145] = { "pet", classes = HUNTER }, -- Dive
    [23147] = 23145,
    [23148] = 23145,
    [1265899] = { "pet", classes = HUNTER }, -- Dust Cloud
    [1265901] = 1265899,
    [1265902] = 1265899,
    [1265903] = 1265899,
    [1265904] = 1265899,
    [6197] = { 14, classes = HUNTER }, -- Eagle Eye
    [1221404] = { 32, classes = HUNTER }, -- Enchanted Flare
    [13813] = { 34, classes = HUNTER }, -- Explosive Trap
    [14316] = 13813,
    [14317] = 13813,
    [1002] = { 14, classes = HUNTER }, -- Eyes of the Beast
    [6991] = { 10, classes = HUNTER }, -- Feed Pet
    [5384] = { 30, classes = HUNTER }, -- Feign Death
    [1543] = { 32, classes = HUNTER }, -- Flare
    [1499] = { 20, classes = HUNTER }, -- Freezing Trap
    [14310] = 1499,
    [14311] = 1499,
    [13809] = { 28, classes = HUNTER }, -- Frost Trap
    [24604] = { "pet", classes = HUNTER }, -- Furious Howl
    [24597] = 24604,
    [24603] = 24604,
    [24605] = 24604,
    [2649] = { "pet", classes = HUNTER }, -- Growl
    [14916] = 2649,
    [14917] = 2649,
    [14918] = 2649,
    [14919] = 2649,
    [14920] = 2649,
    [14921] = 2649,
    [1130] = { 6, classes = HUNTER }, -- Hunter's Mark
    [14323] = 1130,
    [14324] = 1130,
    [14325] = 1130,
    [13795] = { 16, classes = HUNTER }, -- Immolation Trap
    [14302] = 13795,
    [14303] = 13795,
    [14304] = 13795,
    [14305] = 13795,
    [24118] = { 30, classes = HUNTER }, -- Lacerate
    [24119] = 24118,
    [24120] = 24118,
    [1299332] = 24118,
    [444678] = { "pet", classes = HUNTER }, -- Lava Breath
    [444681] = 444678,
    [24844] = { "pet", classes = HUNTER }, -- Lightning Breath
    [25008] = 24844,
    [25009] = 24844,
    [25010] = 24844,
    [25011] = 24844,
    [25012] = 24844,
    [136] = { 12, classes = HUNTER }, -- Mend Pet
    [3111] = 136,
    [3661] = 136,
    [3662] = 136,
    [13542] = 136,
    [13543] = 136,
    [13544] = 136,
    [1265054] = { "pet", classes = HUNTER }, -- Mine!
    [1265055] = 1265054,
    [1265056] = 1265054,
    [1265057] = 1265054,
    [1265058] = 1265054,
    [1495] = { 16, classes = HUNTER }, -- Mongoose Bite
    [14269] = 1495,
    [14270] = 1495,
    [14271] = 1495,
    [2643] = { 18, classes = HUNTER }, -- Multi-Shot
    [1264735] = { "pet", classes = HUNTER }, -- Pinch
    [1264736] = 1264735,
    [1264739] = 1264735,
    [1264741] = 1264735,
    [1264742] = 1264735,
    [24450] = { "pet", classes = HUNTER }, -- Prowl
    [24452] = 24450,
    [24453] = 24450,
    [3045] = { 26, classes = HUNTER }, -- Rapid Fire
    [2973] = { 1, classes = HUNTER }, -- Raptor Strike
    [14260] = 2973,
    [14261] = 2973,
    [14262] = 2973,
    [14263] = 2973,
    [14264] = 2973,
    [14265] = 2973,
    [14266] = 2973,
    [409691] = 2973,
    [409693] = 2973,
    [409748] = 2973,
    [409750] = 2973,
    [409751] = 2973,
    [409752] = 2973,
    [409754] = 2973,
    [409755] = 2973,
    [415335] = 2973,
    [415336] = 2973,
    [415337] = 2973,
    [415338] = 2973,
    [415340] = 2973,
    [415341] = 2973,
    [415342] = 2973,
    [415343] = 2973,
    [982] = { 10, classes = HUNTER }, -- Revive Pet
    [1265065] = { "pet", classes = HUNTER }, -- Savage Rend
    [1265066] = 1265065,
    [1265067] = 1265065,
    [1265068] = 1265065,
    [1265069] = 1265065,
    [1513] = { 14, classes = HUNTER }, -- Scare Beast
    [14326] = 1513,
    [14327] = 1513,
    [24640] = { "pet", classes = HUNTER }, -- Scorpid Poison
    [24583] = 24640,
    [24586] = 24640,
    [24587] = 24640,
    [3043] = { 22, classes = HUNTER }, -- Scorpid Sting
    [1978] = { 4, classes = HUNTER }, -- Serpent Sting
    [13549] = 1978,
    [13550] = 1978,
    [13551] = 1978,
    [13552] = 1978,
    [13553] = 1978,
    [13554] = 1978,
    [13555] = 1978,
    [25295] = 1978,
    [425728] = 1978,
    [425729] = 1978,
    [425730] = 1978,
    [425732] = 1978,
    [425733] = 1978,
    [425734] = 1978,
    [425735] = 1978,
    [425736] = 1978,
    [425737] = 1978,
    [26064] = { "pet", classes = HUNTER }, -- Shell Shield
    [1310785] = { 48, classes = HUNTER }, -- Sniper Shot
    [1310786] = 1310785,
    [1293525] = { 36, classes = HUNTER }, -- Summon Hawk
    [1293526] = 1293525,
    [1293527] = 1293525,
    [1264494] = { "pet", classes = HUNTER }, -- Swipe
    [1264497] = 1264494,
    [1264498] = 1264494,
    [1264501] = 1264494,
    [1264502] = 1264494,
    [1515] = { 10, classes = HUNTER }, -- Tame Beast
    [1265038] = { "pet", classes = HUNTER }, -- Tendon Rip
    [1265039] = 1265038,
    [1265040] = 1265038,
    [1265041] = 1265038,
    [1265042] = 1265038,
    [26090] = { "pet", classes = HUNTER }, -- Thunderstomp
    [26187] = 26090,
    [26188] = 26090,
    [1264455] = 26090,
    [19878] = { 32, classes = HUNTER }, -- Track Demons
    [19879] = { 50, classes = HUNTER }, -- Track Dragonkin
    [19880] = { 26, classes = HUNTER }, -- Track Elementals
    [19882] = { 40, classes = HUNTER }, -- Track Giants
    [19885] = { 24, classes = HUNTER }, -- Track Hidden
    [19883] = { 10, classes = HUNTER }, -- Track Humanoids
    [19884] = { 18, classes = HUNTER }, -- Track Undead
    [19801] = { 60, classes = HUNTER }, -- Tranquilizing Shot
    [1299348] = { 32, classes = HUNTER }, -- Trueshot Aura
    [19506] = 1299348,
    [20905] = 1299348,
    [20906] = 1299348,
    [3034] = { 36, classes = HUNTER }, -- Viper Sting
    [14279] = 3034,
    [14280] = 3034,
    [1510] = { 40, classes = HUNTER }, -- Volley
    [14294] = 1510,
    [14295] = 1510,
    [1265843] = { "pet", classes = HUNTER }, -- Web
    [1265878] = 1265843,
    [1265880] = 1265843,
    [1265881] = 1265843,
    [1265883] = 1265843,
    [2974] = { 12, classes = HUNTER }, -- Wing Clip
    [14267] = 2974,
    [14268] = 2974,
    [1008] = { 18, classes = MAGE }, -- Amplify Magic
    [8455] = 1008,
    [10169] = 1008,
    [10170] = 1008,
    [1239696] = { 30, classes = MAGE }, -- Arcane Blast
    [1239697] = 1239696,
    [1239699] = 1239696,
    [1239700] = 1239696,
    [23028] = { 56, classes = MAGE }, -- Arcane Brilliance
    [1449] = { 14, classes = MAGE }, -- Arcane Explosion
    [8437] = 1449,
    [8438] = 1449,
    [8439] = 1449,
    [10201] = 1449,
    [10202] = 1449,
    [1459] = { 1, classes = MAGE }, -- Arcane Intellect
    [1460] = 1459,
    [1461] = 1459,
    [10156] = 1459,
    [10157] = 1459,
    [5143] = { 8, classes = MAGE }, -- Arcane Missiles
    [5144] = 5143,
    [5145] = 5143,
    [8416] = 5143,
    [8417] = 5143,
    [10211] = 5143,
    [10212] = 5143,
    [25345] = 5143,
    [13018] = { 36, classes = MAGE }, -- Blast Wave
    [13019] = 13018,
    [13020] = 13018,
    [13021] = 13018,
    [1953] = { 20, classes = MAGE }, -- Blink
    [10] = { 20, classes = MAGE }, -- Blizzard
    [6141] = 10,
    [8427] = 10,
    [10185] = 10,
    [10186] = 10,
    [10187] = 10,
    [120] = { 26, classes = MAGE }, -- Cone of Cold
    [8492] = 120,
    [10159] = 120,
    [10160] = 120,
    [10161] = 120,
    [587] = { 6, classes = MAGE }, -- Conjure Food
    [597] = 587,
    [990] = 587,
    [6129] = 587,
    [10144] = 587,
    [10145] = 587,
    [28612] = 587,
    [759] = { 28, classes = MAGE }, -- Conjure Mana Agate
    [10053] = { 48, classes = MAGE }, -- Conjure Mana Citrine
    [3552] = { 38, classes = MAGE }, -- Conjure Mana Jade
    [10054] = { 58, classes = MAGE }, -- Conjure Mana Ruby
    [5504] = { 4, classes = MAGE }, -- Conjure Water
    [5505] = 5504,
    [5506] = 5504,
    [6127] = 5504,
    [10138] = 5504,
    [10139] = 5504,
    [10140] = 5504,
    [468766] = 5504,
    [2139] = { 24, classes = MAGE }, -- Counterspell
    [604] = { 12, classes = MAGE }, -- Dampen Magic
    [8450] = 604,
    [8451] = 604,
    [10173] = 604,
    [10174] = 604,
    [12051] = { 20, classes = MAGE }, -- Evocation
    [2136] = { 6, classes = MAGE }, -- Fire Blast
    [2137] = 2136,
    [2138] = 2136,
    [8412] = 2136,
    [8413] = 2136,
    [10197] = 2136,
    [10199] = 2136,
    [400616] = 2136,
    [400618] = 2136,
    [400619] = 2136,
    [400620] = 2136,
    [400621] = 2136,
    [400622] = 2136,
    [400623] = 2136,
    [543] = { 20, classes = MAGE }, -- Fire Ward
    [8457] = 543,
    [8458] = 543,
    [10223] = 543,
    [10225] = 543,
    [133] = { 1, classes = MAGE }, -- Fireball
    [143] = 133,
    [145] = 133,
    [3140] = 133,
    [8400] = 133,
    [8401] = 133,
    [8402] = 133,
    [10148] = 133,
    [10149] = 133,
    [10150] = 133,
    [10151] = 133,
    [25306] = 133,
    [2120] = { 16, classes = MAGE }, -- Flamestrike
    [2121] = 2120,
    [8422] = 2120,
    [8423] = 2120,
    [10215] = 2120,
    [10216] = 2120,
    [168] = { 1, classes = MAGE }, -- Frost Armor
    [7300] = 168,
    [7301] = 168,
    [122] = { 10, classes = MAGE }, -- Frost Nova
    [865] = 122,
    [6131] = 122,
    [10230] = 122,
    [6143] = { 22, classes = MAGE }, -- Frost Ward
    [8461] = 6143,
    [8462] = 6143,
    [10177] = 6143,
    [28609] = 6143,
    [116] = { 4, classes = MAGE }, -- Frostbolt
    [205] = 116,
    [837] = 116,
    [7322] = 116,
    [8406] = 116,
    [8407] = 116,
    [8408] = 116,
    [10179] = 116,
    [10180] = 116,
    [10181] = 116,
    [25304] = 116,
    [401502] = { 40, classes = MAGE }, -- Frostfire Bolt
    [1237312] = 401502,
    [1237313] = 401502,
    [7302] = { 30, classes = MAGE }, -- Ice Armor
    [7320] = 7302,
    [10219] = 7302,
    [10220] = 7302,
    [13031] = { 46, classes = MAGE }, -- Ice Barrier
    [13032] = 13031,
    [13033] = 13031,
    [400640] = { 28, classes = MAGE }, -- Ice Lance
    [1240044] = 400640,
    [1240045] = 400640,
    [1240046] = 400640,
    [1240047] = 400640,
    [6117] = { 34, classes = MAGE }, -- Mage Armor
    [22782] = 6117,
    [22783] = 6117,
    [1463] = { 20, classes = MAGE }, -- Mana Shield
    [8494] = 1463,
    [8495] = 1463,
    [10191] = 1463,
    [10192] = 1463,
    [10193] = 1463,
    [118] = { 8, classes = MAGE }, -- Polymorph
    [12824] = 118,
    [12825] = 118,
    [12826] = 118,
    [28271] = 118,
    [28272] = 118,
    [28270] = { 60, classes = MAGE }, -- Polymorph: Cow
    [11419] = { 50, classes = MAGE }, -- Portal: Darnassus
    [11416] = { 40, classes = MAGE }, -- Portal: Ironforge
    [11417] = { 40, classes = MAGE }, -- Portal: Orgrimmar
    [10059] = { 40, classes = MAGE }, -- Portal: Stormwind
    [11420] = { 50, classes = MAGE }, -- Portal: Thunder Bluff
    [11418] = { 40, classes = MAGE }, -- Portal: Undercity
    [12505] = { 24, classes = MAGE }, -- Pyroblast
    [12522] = 12505,
    [12523] = 12505,
    [12524] = 12505,
    [12525] = 12505,
    [12526] = 12505,
    [18809] = 12505,
    [475] = { 18, classes = MAGE }, -- Remove Lesser Curse
    [2948] = { 22, classes = MAGE }, -- Scorch
    [8444] = 2948,
    [8445] = 2948,
    [8446] = 2948,
    [10205] = 2948,
    [10206] = 2948,
    [10207] = 2948,
    [130] = { 12, classes = MAGE }, -- Slow Fall
    [1297659] = { 50, classes = MAGE }, -- Teleport: Dalaran
    [3565] = { 30, classes = MAGE }, -- Teleport: Darnassus
    [3562] = { 20, classes = MAGE }, -- Teleport: Ironforge
    [3567] = { 20, classes = MAGE }, -- Teleport: Orgrimmar
    [3561] = { 20, classes = MAGE }, -- Teleport: Stormwind
    [3566] = { 30, classes = MAGE }, -- Teleport: Thunder Bluff
    [3563] = { 20, classes = MAGE }, -- Teleport: Undercity
    [1044] = { 18, classes = PALADIN }, -- Blessing of Freedom
    [20217] = { 20, classes = PALADIN }, -- Blessing of Kings
    [19977] = { 40, classes = PALADIN }, -- Blessing of Light
    [19978] = 19977,
    [19979] = 19977,
    [19740] = { 4, classes = PALADIN }, -- Blessing of Might
    [19834] = 19740,
    [19835] = 19740,
    [19836] = 19740,
    [19837] = 19740,
    [19838] = 19740,
    [25291] = 19740,
    [1022] = { 10, classes = PALADIN }, -- Blessing of Protection
    [5599] = 1022,
    [10278] = 1022,
    [6940] = { 46, classes = PALADIN }, -- Blessing of Sacrifice
    [20729] = 6940,
    [1038] = { 26, classes = PALADIN }, -- Blessing of Salvation
    [19742] = { 14, classes = PALADIN }, -- Blessing of Wisdom
    [19850] = 19742,
    [19852] = 19742,
    [19853] = 19742,
    [19854] = 19742,
    [25290] = 19742,
    [4987] = { 42, classes = PALADIN }, -- Cleanse
    [19746] = { 22, classes = PALADIN }, -- Concentration Aura
    [26573] = { 20, classes = PALADIN }, -- Consecration
    [20116] = 26573,
    [20922] = 26573,
    [20923] = 26573,
    [20924] = 26573,
    [465] = { 1, classes = PALADIN }, -- Devotion Aura
    [643] = 465,
    [1032] = 465,
    [10290] = 465,
    [10291] = 465,
    [10292] = 465,
    [10293] = 465,
    [19752] = { 30, classes = PALADIN }, -- Divine Intervention
    [498] = { 6, classes = PALADIN }, -- Divine Protection
    [5573] = 498,
    [642] = { 34, classes = PALADIN }, -- Divine Shield
    [1020] = 642,
    [879] = { 20, classes = PALADIN }, -- Exorcism
    [5614] = 879,
    [5615] = 879,
    [10312] = 879,
    [10313] = 879,
    [10314] = 879,
    [415068] = 879,
    [415069] = 879,
    [415070] = 879,
    [415071] = 879,
    [415072] = 879,
    [415073] = 879,
    [19891] = { 36, classes = PALADIN }, -- Fire Resistance Aura
    [19899] = 19891,
    [19900] = 19891,
    [412020] = { 1, classes = PALADIN }, -- Flash of Light
    [19750] = 412020,
    [19939] = 412020,
    [19940] = 412020,
    [19941] = 412020,
    [19942] = 412020,
    [19943] = 412020,
    [1313342] = 412020,
    [1313343] = 412020,
    [1313344] = 412020,
    [1313345] = 412020,
    [1313346] = 412020,
    [19888] = { 32, classes = PALADIN }, -- Frost Resistance Aura
    [19897] = 19888,
    [19898] = 19888,
    [25898] = { 60, classes = PALADIN }, -- Greater Blessing of Kings
    [25890] = { 60, classes = PALADIN }, -- Greater Blessing of Light
    [25782] = { 52, classes = PALADIN }, -- Greater Blessing of Might
    [25916] = 25782,
    [25895] = { 60, classes = PALADIN }, -- Greater Blessing of Salvation
    [25894] = { 54, classes = PALADIN }, -- Greater Blessing of Wisdom
    [25918] = 25894,
    [853] = { 8, classes = PALADIN }, -- Hammer of Justice
    [5588] = 853,
    [5589] = 853,
    [10308] = 853,
    [24275] = { 44, classes = PALADIN }, -- Hammer of Wrath
    [24239] = 24275,
    [24274] = 24275,
    [635] = { 1, classes = PALADIN }, -- Holy Light
    [639] = 635,
    [647] = 635,
    [1026] = 635,
    [1042] = 635,
    [3472] = 635,
    [10328] = 635,
    [10329] = 635,
    [25292] = 635,
    [1313348] = 635,
    [1313349] = 635,
    [1313350] = 635,
    [1313351] = 635,
    [1313352] = 635,
    [20927] = { 50, classes = PALADIN }, -- Holy Shield
    [20928] = 20927,
    [20473] = { 40, classes = PALADIN }, -- Holy Shock
    [20929] = 20473,
    [20930] = 20473,
    [679] = { 6, classes = PALADIN }, -- Holy Strike
    [678] = 679,
    [680] = 679,
    [1866] = 679,
    [2495] = 679,
    [5569] = 679,
    [10332] = 679,
    [10333] = 679,
    [2812] = { 50, classes = PALADIN }, -- Holy Wrath
    [10318] = 2812,
    [20271] = { 4, classes = PALADIN }, -- Judgement
    [20183] = { 25, classes = PALADIN }, -- Judgement of Fury
    [20411] = 20183,
    [20412] = 20183,
    [20413] = 20183,
    [20414] = 20183,
    [633] = { 10, classes = PALADIN }, -- Lay on Hands
    [2800] = 633,
    [10310] = 633,
    [1311590] = { 50, classes = PALADIN }, -- Light's Vigil
    [1311595] = 1311590,
    [1152] = { 8, classes = PALADIN }, -- Purify
    [7328] = { 12, classes = PALADIN }, -- Redemption
    [10322] = 7328,
    [10324] = 7328,
    [20772] = 7328,
    [20773] = 7328,
    [7294] = { 16, classes = PALADIN }, -- Retribution Aura
    [10298] = 7294,
    [10299] = 7294,
    [10300] = 7294,
    [10301] = 7294,
    [407627] = { 1, classes = PALADIN }, -- Righteous Fury
    [25780] = 407627,
    [20915] = { 30, classes = PALADIN }, -- Seal of Command
    [20918] = 20915,
    [20919] = 20915,
    [20920] = 20915,
    [1311649] = { 10, classes = PALADIN }, -- Seal of Fury
    [20163] = 1311649,
    [20419] = 1311649,
    [20421] = 1311649,
    [20422] = 1311649,
    [20423] = 1311649,
    [1311656] = 1311649,
    [20164] = { 22, classes = PALADIN }, -- Seal of Justice
    [20165] = { 30, classes = PALADIN }, -- Seal of Light
    [20347] = 20165,
    [20348] = 20165,
    [20349] = 20165,
    [20154] = { 1, classes = PALADIN }, -- Seal of Righteousness
    [20287] = 20154,
    [20288] = 20154,
    [20289] = 20154,
    [20290] = 20154,
    [20291] = 20154,
    [20292] = 20154,
    [20293] = 20154,
    [21084] = 20154,
    [21082] = { 6, classes = PALADIN }, -- Seal of the Crusader
    [20162] = 21082,
    [20305] = 21082,
    [20306] = 21082,
    [20307] = 21082,
    [20308] = 21082,
    [20166] = { 38, classes = PALADIN }, -- Seal of Wisdom
    [20356] = 20166,
    [20357] = 20166,
    [5502] = { 20, classes = PALADIN }, -- Sense Undead
    [19876] = { 28, classes = PALADIN }, -- Shadow Resistance Aura
    [19895] = 19876,
    [19896] = 19876,
    [2878] = { 24, classes = PALADIN }, -- Turn Undead
    [5627] = 2878,
    [10326] = 2878,
    [552] = { 32, classes = PRIEST }, -- Abolish Disease
    [1240770] = { 32, classes = PRIEST }, -- Binding Heal
    [1240771] = 1240770,
    [1240772] = 1240770,
    [1240773] = 1240770,
    [1240774] = 1240770,
    [1277331] = { 20, classes = PRIEST }, -- Chastise
    [1277332] = 1277331,
    [1277333] = 1277331,
    [1277334] = 1277331,
    [1277335] = 1277331,
    [1277455] = { 10, classes = PRIEST }, -- Confounding Flash
    [1277462] = { 20, classes = PRIEST }, -- Contingency Plan
    [1277634] = 1277462,
    [1277638] = 1277462,
    [1277639] = 1277462,
    [1277640] = 1277462,
    [528] = { 14, classes = PRIEST }, -- Cure Disease
    [1277324] = { 20, classes = PRIEST }, -- Dark Sacrifice
    [1277325] = 1277324,
    [1277326] = 1277324,
    [1277327] = 1277324,
    [1277328] = 1277324,
    [13908] = { 10, classes = PRIEST }, -- Desperate Prayer
    [19236] = 13908,
    [19238] = 13908,
    [19240] = 13908,
    [19241] = 13908,
    [19242] = 13908,
    [19243] = 13908,
    [2944] = { 20, classes = PRIEST }, -- Devouring Plague
    [19276] = 2944,
    [19277] = 2944,
    [19278] = 2944,
    [19279] = 2944,
    [19280] = 2944,
    [527] = { 18, classes = PRIEST }, -- Dispel Magic
    [988] = 527,
    [1277370] = { 10, classes = PRIEST }, -- Divine Grace
    [1277371] = 1277370,
    [1277372] = 1277370,
    [1277374] = 1277370,
    [1277376] = 1277370,
    [1277377] = 1277370,
    [1277378] = 1277370,
    [14752] = { 30, classes = PRIEST }, -- Divine Spirit
    [14818] = 14752,
    [14819] = 14752,
    [27841] = 14752,
    [2651] = { 20, classes = PRIEST }, -- Elune's Grace
    [586] = { 8, classes = PRIEST }, -- Fade
    [9578] = 586,
    [9579] = 586,
    [9592] = 586,
    [10941] = 586,
    [10942] = 586,
    [6346] = { 20, classes = PRIEST }, -- Fear Ward
    [13896] = { 20, classes = PRIEST }, -- Feedback
    [19271] = 13896,
    [19273] = 13896,
    [19274] = 13896,
    [19275] = 13896,
    [2061] = { 20, classes = PRIEST }, -- Flash Heal
    [9472] = 2061,
    [9473] = 2061,
    [9474] = 2061,
    [10915] = 2061,
    [10916] = 2061,
    [10917] = 2061,
    [2060] = { 40, classes = PRIEST }, -- Greater Heal
    [10963] = 2060,
    [10964] = 2060,
    [10965] = 2060,
    [25314] = 2060,
    [2054] = { 16, classes = PRIEST }, -- Heal
    [2055] = 2054,
    [6063] = 2054,
    [6064] = 2054,
    [9035] = { 10, classes = PRIEST }, -- Hex of Weakness
    [19281] = 9035,
    [19282] = 9035,
    [19283] = 9035,
    [19284] = 9035,
    [19285] = 9035,
    [14914] = { 20, classes = PRIEST }, -- Holy Fire
    [15261] = 14914,
    [15262] = 14914,
    [15263] = 14914,
    [15264] = 14914,
    [15265] = 14914,
    [15266] = 14914,
    [15267] = 14914,
    [15430] = { 28, classes = PRIEST }, -- Holy Nova
    [15431] = 15430,
    [27799] = 15430,
    [27800] = 15430,
    [27801] = 15430,
    [588] = { 12, classes = PRIEST }, -- Inner Fire
    [602] = 588,
    [1006] = 588,
    [7128] = 588,
    [10951] = 588,
    [10952] = 588,
    [2050] = { 1, classes = PRIEST }, -- Lesser Heal
    [2052] = 2050,
    [2053] = 2050,
    [1706] = { 34, classes = PRIEST }, -- Levitate
    [724] = { 40, classes = PRIEST }, -- Lightwell
    [27870] = 724,
    [27871] = 724,
    [8129] = { 24, classes = PRIEST }, -- Mana Burn
    [8131] = 8129,
    [10874] = 8129,
    [10875] = 8129,
    [10876] = 8129,
    [8092] = { 10, classes = PRIEST }, -- Mind Blast
    [8102] = 8092,
    [8103] = 8092,
    [8104] = 8092,
    [8105] = 8092,
    [8106] = 8092,
    [10945] = 8092,
    [10946] = 8092,
    [10947] = 8092,
    [605] = { 30, classes = PRIEST }, -- Mind Control
    [10911] = 605,
    [10912] = 605,
    [17311] = { 28, classes = PRIEST }, -- Mind Flay
    [17312] = 17311,
    [17313] = 17311,
    [17314] = 17311,
    [18807] = 17311,
    [453] = { 20, classes = PRIEST }, -- Mind Soothe
    [8192] = 453,
    [10953] = 453,
    [2096] = { 22, classes = PRIEST }, -- Mind Vision
    [10909] = 2096,
    [402284] = { 30, classes = PRIEST }, -- Penance
    [402289] = 402284,
    [1240720] = 402284,
    [1240721] = 402284,
    [1240723] = 402284,
    [1240724] = 402284,
    [1240727] = 402284,
    [1240730] = 402284,
    [1316991] = 402284,
    [1316993] = 402284,
    [1316995] = 402284,
    [1243] = { 1, classes = PRIEST }, -- Power Word: Fortitude
    [1244] = 1243,
    [1245] = 1243,
    [2791] = 1243,
    [10937] = 1243,
    [10938] = 1243,
    [17] = { 6, classes = PRIEST }, -- Power Word: Shield
    [592] = 17,
    [600] = 17,
    [3747] = 17,
    [6065] = 17,
    [6066] = 17,
    [10898] = 17,
    [10899] = 17,
    [10900] = 17,
    [10901] = 17,
    [21562] = { 48, classes = PRIEST }, -- Prayer of Fortitude
    [21564] = 21562,
    [596] = { 30, classes = PRIEST }, -- Prayer of Healing
    [996] = 596,
    [10960] = 596,
    [10961] = 596,
    [25316] = 596,
    [401863] = { 40, classes = PRIEST }, -- Prayer of Mending
    [1240826] = 401863,
    [1240827] = 401863,
    [27683] = { 56, classes = PRIEST }, -- Prayer of Shadow Protection
    [27681] = { 60, classes = PRIEST }, -- Prayer of Spirit
    [8122] = { 14, classes = PRIEST }, -- Psychic Scream
    [8124] = 8122,
    [10888] = 8122,
    [10890] = 8122,
    [139] = { 8, classes = PRIEST }, -- Renew
    [6074] = 139,
    [6075] = 139,
    [6076] = 139,
    [6077] = 139,
    [6078] = 139,
    [10927] = 139,
    [10928] = 139,
    [10929] = 139,
    [25315] = 139,
    [425268] = 139,
    [425269] = 139,
    [425270] = 139,
    [425271] = 139,
    [425272] = 139,
    [425273] = 139,
    [425274] = 139,
    [425275] = 139,
    [425276] = 139,
    [425277] = 139,
    [2006] = { 10, classes = PRIEST }, -- Resurrection
    [2010] = 2006,
    [10880] = 2006,
    [10881] = 2006,
    [20770] = 2006,
    [9484] = { 20, classes = PRIEST }, -- Shackle Undead
    [9485] = 9484,
    [10955] = 9484,
    [976] = { 30, classes = PRIEST }, -- Shadow Protection
    [10957] = 976,
    [10958] = 976,
    [401955] = { 1, classes = PRIEST }, -- Shadow Word: Death
    [1309595] = 401955,
    [1309633] = 401955,
    [1309635] = 401955,
    [1309636] = 401955,
    [589] = { 4, classes = PRIEST }, -- Shadow Word: Pain
    [594] = 589,
    [970] = 589,
    [992] = 589,
    [2767] = 589,
    [10892] = 589,
    [10893] = 589,
    [10894] = 589,
    [18137] = { 20, classes = PRIEST }, -- Shadowguard
    [19308] = 18137,
    [19309] = 18137,
    [19310] = 18137,
    [19311] = 18137,
    [19312] = 18137,
    [585] = { 1, classes = PRIEST }, -- Smite
    [591] = 585,
    [598] = 585,
    [984] = 585,
    [1004] = 585,
    [6060] = 585,
    [10933] = 585,
    [10934] = 585,
    [10797] = { 10, classes = PRIEST }, -- Starshards
    [19296] = 10797,
    [19299] = 10797,
    [19302] = 10797,
    [19303] = 10797,
    [19304] = 10797,
    [19305] = 10797,
    [2652] = { 10, classes = PRIEST }, -- Touch of Weakness
    [19261] = 2652,
    [19262] = 2652,
    [19264] = 2652,
    [19265] = 2652,
    [19266] = 2652,
    [8676] = { 18, classes = ROGUE }, -- Ambush
    [8724] = 8676,
    [8725] = 8676,
    [11267] = 8676,
    [11268] = 8676,
    [11269] = 8676,
    [53] = { 4, classes = ROGUE }, -- Backstab
    [2589] = 53,
    [2590] = 53,
    [2591] = 53,
    [8721] = 53,
    [11279] = 53,
    [11280] = 53,
    [11281] = 53,
    [25300] = 53,
    [2094] = { 34, classes = ROGUE }, -- Blind
    [1833] = { 26, classes = ROGUE }, -- Cheap Shot
    [1842] = { 30, classes = ROGUE }, -- Disarm Trap
    [1725] = { 22, classes = ROGUE }, -- Distract
    [5277] = { 8, classes = ROGUE }, -- Evasion
    [2098] = { 1, classes = ROGUE }, -- Eviscerate
    [6760] = 2098,
    [6761] = 2098,
    [6762] = 2098,
    [8623] = 2098,
    [8624] = 2098,
    [11299] = 2098,
    [11300] = 2098,
    [31016] = 2098,
    [8647] = { 14, classes = ROGUE }, -- Expose Armor
    [8649] = 8647,
    [8650] = 8647,
    [11197] = 8647,
    [11198] = 8647,
    [1966] = { 16, classes = ROGUE }, -- Feint
    [6768] = 1966,
    [8637] = 1966,
    [11303] = 1966,
    [25302] = 1966,
    [703] = { 14, classes = ROGUE }, -- Garrote
    [8631] = 703,
    [8632] = 703,
    [8633] = 703,
    [11289] = 703,
    [11290] = 703,
    [1776] = { 6, classes = ROGUE }, -- Gouge
    [1777] = 1776,
    [8629] = 1776,
    [11285] = 1776,
    [11286] = 1776,
    [1766] = { 12, classes = ROGUE }, -- Kick
    [1767] = 1766,
    [1768] = 1766,
    [1769] = 1766,
    [408] = { 30, classes = ROGUE }, -- Kidney Shot
    [8643] = 408,
    [399956] = { 40, classes = ROGUE }, -- Mutilate
    [1241582] = 399956,
    [1241584] = 399956,
    [921] = { 4, classes = ROGUE }, -- Pick Pocket
    [1943] = { 20, classes = ROGUE }, -- Rupture
    [8639] = 1943,
    [8640] = 1943,
    [11273] = 1943,
    [11274] = 1943,
    [11275] = 1943,
    [6770] = { 10, classes = ROGUE }, -- Sap
    [2070] = 6770,
    [11297] = 6770,
    [1752] = { 1, classes = ROGUE }, -- Sinister Strike
    [1757] = 1752,
    [1758] = 1752,
    [1759] = 1752,
    [1760] = 1752,
    [8621] = 1752,
    [11293] = 1752,
    [11294] = 1752,
    [5171] = { 10, classes = ROGUE }, -- Slice and Dice
    [6774] = 5171,
    [2983] = { 10, classes = ROGUE }, -- Sprint
    [8696] = 2983,
    [11305] = 2983,
    [1784] = { 1, classes = ROGUE }, -- Stealth
    [1785] = 1784,
    [1786] = 1784,
    [1787] = 1784,
    [1856] = { 22, classes = ROGUE }, -- Vanish
    [1857] = 1856,
    [2008] = { 12, classes = SHAMAN }, -- Ancestral Spirit
    [20609] = 2008,
    [20610] = 2008,
    [20776] = 2008,
    [20777] = 2008,
    [556] = { 30, classes = SHAMAN }, -- Astral Recall
    [66843] = { 30, classes = SHAMAN }, -- Call of the Ancestors
    [66842] = { 20, classes = SHAMAN }, -- Call of the Elements
    [66844] = { 40, classes = SHAMAN }, -- Call of the Spirits
    [1064] = { 40, classes = SHAMAN }, -- Chain Heal
    [10622] = 1064,
    [10623] = 1064,
    [421] = { 32, classes = SHAMAN }, -- Chain Lightning
    [930] = 421,
    [2860] = 421,
    [10605] = 421,
    [408479] = 421,
    [408481] = 421,
    [408482] = 421,
    [408484] = 421,
    [2870] = { 22, classes = SHAMAN }, -- Cure Disease
    [526] = { 16, classes = SHAMAN }, -- Cure Poison
    [8170] = { 38, classes = SHAMAN }, -- Disease Cleansing Totem
    [8042] = { 4, classes = SHAMAN }, -- Earth Shock
    [8044] = 8042,
    [8045] = 8042,
    [8046] = 8042,
    [10412] = 8042,
    [10413] = 8042,
    [10414] = 8042,
    [2484] = { 6, classes = SHAMAN }, -- Earthbind Totem
    [6196] = { 26, classes = SHAMAN }, -- Far Sight
    [408341] = { 12, classes = SHAMAN }, -- Fire Nova
    [408342] = 408341,
    [408343] = 408341,
    [408344] = 408341,
    [408345] = 408341,
    [8184] = { 28, classes = SHAMAN }, -- Fire Resistance Totem
    [10537] = 8184,
    [10538] = 8184,
    [8050] = { 10, classes = SHAMAN }, -- Flame Shock
    [8052] = 8050,
    [8053] = 8050,
    [10447] = 8050,
    [10448] = 8050,
    [29228] = 8050,
    [8227] = { 28, classes = SHAMAN }, -- Flametongue Totem
    [8249] = 8227,
    [10526] = 8227,
    [16387] = 8227,
    [8024] = { 10, classes = SHAMAN }, -- Flametongue Weapon
    [8027] = 8024,
    [8030] = 8024,
    [16339] = 8024,
    [16341] = 8024,
    [16342] = 8024,
    [8181] = { 24, classes = SHAMAN }, -- Frost Resistance Totem
    [10478] = 8181,
    [10479] = 8181,
    [8056] = { 20, classes = SHAMAN }, -- Frost Shock
    [8058] = 8056,
    [10472] = 8056,
    [10473] = 8056,
    [8033] = { 20, classes = SHAMAN }, -- Frostbrand Weapon
    [8038] = 8033,
    [10456] = 8033,
    [16355] = 8033,
    [16356] = 8033,
    [2645] = { 20, classes = SHAMAN }, -- Ghost Wolf
    [8835] = { 42, classes = SHAMAN }, -- Grace of Air Totem
    [10627] = 8835,
    [25359] = 8835,
    [8177] = { 30, classes = SHAMAN }, -- Grounding Totem
    [5394] = { 20, classes = SHAMAN }, -- Healing Stream Totem
    [6375] = 5394,
    [6377] = 5394,
    [10462] = 5394,
    [10463] = 5394,
    [331] = { 1, classes = SHAMAN }, -- Healing Wave
    [332] = 331,
    [547] = 331,
    [913] = 331,
    [939] = 331,
    [959] = 331,
    [8005] = 331,
    [10395] = 331,
    [10396] = 331,
    [25357] = 331,
    [408491] = { 40, classes = SHAMAN }, -- Lava Burst
    [1238299] = 408491,
    [1238300] = 408491,
    [1238373] = 408491,
    [1238376] = 408491,
    [8004] = { 20, classes = SHAMAN }, -- Lesser Healing Wave
    [8008] = 8004,
    [8010] = 8004,
    [10466] = 8004,
    [10467] = 8004,
    [10468] = 8004,
    [403] = { 1, classes = SHAMAN }, -- Lightning Bolt
    [529] = 403,
    [548] = 403,
    [915] = 403,
    [943] = 403,
    [6041] = 403,
    [10391] = 403,
    [10392] = 403,
    [15207] = 403,
    [15208] = 403,
    [408439] = 403,
    [408440] = 403,
    [408441] = 403,
    [408442] = 403,
    [408443] = 403,
    [408472] = 403,
    [408473] = 403,
    [408474] = 403,
    [408475] = 403,
    [408477] = 403,
    [324] = { 8, classes = SHAMAN }, -- Lightning Shield
    [325] = 324,
    [905] = 324,
    [945] = 324,
    [8134] = 324,
    [10431] = 324,
    [10432] = 324,
    [8190] = { 26, classes = SHAMAN }, -- Magma Totem
    [10585] = 8190,
    [10586] = 8190,
    [10587] = 8190,
    [5675] = { 26, classes = SHAMAN }, -- Mana Spring Totem
    [10495] = 5675,
    [10496] = 5675,
    [10497] = 5675,
    [17354] = { 48, classes = SHAMAN }, -- Mana Tide Totem
    [17359] = 17354,
    [10595] = { 30, classes = SHAMAN }, -- Nature Resistance Totem
    [10600] = 10595,
    [10601] = 10595,
    [8166] = { 22, classes = SHAMAN }, -- Poison Cleansing Totem
    [370] = { 12, classes = SHAMAN }, -- Purge
    [8012] = 370,
    [1239242] = { 50, classes = SHAMAN }, -- Riptide
    [1239243] = 1239242,
    [8017] = { 1, classes = SHAMAN }, -- Rockbiter Weapon
    [8018] = 8017,
    [8019] = 8017,
    [10399] = 8017,
    [16314] = 8017,
    [16315] = 8017,
    [16316] = 8017,
    [3599] = { 10, classes = SHAMAN }, -- Searing Totem
    [6363] = 3599,
    [6364] = 3599,
    [6365] = 3599,
    [10437] = 3599,
    [10438] = 3599,
    [6495] = { 34, classes = SHAMAN }, -- Sentry Totem
    [5730] = { 8, classes = SHAMAN }, -- Stoneclaw Totem
    [6390] = 5730,
    [6391] = 5730,
    [6392] = 5730,
    [10427] = 5730,
    [10428] = 5730,
    [8071] = { 4, classes = SHAMAN }, -- Stoneskin Totem
    [8154] = 8071,
    [8155] = 8071,
    [10406] = 8071,
    [10407] = 8071,
    [10408] = 8071,
    [8075] = { 10, classes = SHAMAN }, -- Strength of Earth Totem
    [8160] = 8075,
    [8161] = 8075,
    [10442] = 8075,
    [25361] = 8075,
    [437009] = { 22, classes = SHAMAN }, -- Totemic Projection
    [36936] = { 20, classes = SHAMAN }, -- Totemic Recall
    [8143] = { 18, classes = SHAMAN }, -- Tremor Totem
    [131] = { 22, classes = SHAMAN }, -- Water Breathing
    [546] = { 28, classes = SHAMAN }, -- Water Walking
    [8512] = { 32, classes = SHAMAN }, -- Windfury Totem
    [10613] = 8512,
    [10614] = 8512,
    [8232] = { 30, classes = SHAMAN }, -- Windfury Weapon
    [8235] = 8232,
    [10486] = 8232,
    [16362] = 8232,
    [15107] = { 36, classes = SHAMAN }, -- Windwall Totem
    [15111] = 15107,
    [15112] = 15107,
    [427742] = { "pet", classes = WARLOCK }, -- Anguish
    [980] = { 8, classes = WARLOCK }, -- Bane of Agony
    [1014] = 980,
    [6217] = 980,
    [11711] = 980,
    [11712] = 980,
    [11713] = 980,
    [603] = { 60, classes = WARLOCK }, -- Bane of Doom
    [710] = { 28, classes = WARLOCK }, -- Banish
    [18647] = 710,
    [6307] = { "pet", classes = WARLOCK }, -- Blood Pact
    [7804] = 6307,
    [7805] = 6307,
    [11766] = 6307,
    [11767] = 6307,
    [427744] = { "pet", classes = WARLOCK }, -- Cleave
    [1293818] = { 32, classes = WARLOCK }, -- Conflagrate
    [17962] = 1293818,
    [18930] = 1293818,
    [18931] = 1293818,
    [18932] = 1293818,
    [17767] = { "pet", classes = WARLOCK }, -- Consume Shadows
    [17850] = 17767,
    [17851] = 17767,
    [17852] = 17767,
    [17853] = 17767,
    [17854] = 17767,
    [172] = { 4, classes = WARLOCK }, -- Corruption
    [6222] = 172,
    [6223] = 172,
    [7648] = 172,
    [11671] = 172,
    [11672] = 172,
    [25311] = 172,
    [6366] = { 28, classes = WARLOCK }, -- Create Firestone
    [17951] = 6366,
    [17952] = 6366,
    [17953] = 6366,
    [6201] = { 10, classes = WARLOCK }, -- Create Healthstone
    [5699] = 6201,
    [6202] = 6201,
    [11729] = 6201,
    [11730] = 6201,
    [693] = { 18, classes = WARLOCK }, -- Create Soulstone
    [20752] = 693,
    [20755] = 693,
    [20756] = 693,
    [20757] = 693,
    [2362] = { 36, classes = WARLOCK }, -- Create Spellstone
    [17727] = 2362,
    [17728] = 2362,
    [704] = { 14, classes = WARLOCK }, -- Curse of Recklessness
    [7658] = 704,
    [7659] = 704,
    [11717] = 704,
    [440892] = { 20, classes = WARLOCK }, -- Curse of the Elements
    [1311676] = 440892,
    [1311677] = 440892,
    [1311680] = 440892,
    [1714] = { 26, classes = WARLOCK }, -- Curse of Tongues
    [11719] = 1714,
    [702] = { 4, classes = WARLOCK }, -- Curse of Weakness
    [1108] = 702,
    [6205] = 702,
    [7646] = 702,
    [11707] = 702,
    [11708] = 702,
    [6789] = { 42, classes = WARLOCK }, -- Death Coil
    [17925] = 6789,
    [17926] = 6789,
    [706] = { 20, classes = WARLOCK }, -- Demon Armor
    [1086] = 706,
    [11733] = 706,
    [11734] = 706,
    [11735] = 706,
    [687] = { 1, classes = WARLOCK }, -- Demon Skin
    [696] = 687,
    [132] = { 26, classes = WARLOCK }, -- Detect Invisibility
    [2970] = 132,
    [11743] = 132,
    [19505] = { "pet", classes = WARLOCK }, -- Devour Magic
    [19731] = 19505,
    [19734] = 19505,
    [19736] = 19505,
    [689] = { 14, classes = WARLOCK }, -- Drain Life
    [699] = 689,
    [709] = 689,
    [7651] = 689,
    [11699] = 689,
    [11700] = 689,
    [403677] = 689,
    [403685] = 689,
    [403686] = 689,
    [403687] = 689,
    [403688] = 689,
    [403689] = 689,
    [5138] = { 24, classes = WARLOCK }, -- Drain Mana
    [6226] = 5138,
    [11703] = 5138,
    [11704] = 5138,
    [1120] = { 10, classes = WARLOCK }, -- Drain Soul
    [8288] = 1120,
    [8289] = 1120,
    [11675] = 1120,
    [126] = { 22, classes = WARLOCK }, -- Eye of Kilrogg
    [5782] = { 8, classes = WARLOCK }, -- Fear
    [6213] = 5782,
    [6215] = 5782,
    [2947] = { "pet", classes = WARLOCK }, -- Fire Shield
    [8316] = 2947,
    [8317] = 2947,
    [11770] = 2947,
    [11771] = 2947,
    [3110] = { "pet", classes = WARLOCK }, -- Firebolt
    [7799] = 3110,
    [7800] = 3110,
    [7801] = 3110,
    [7802] = 3110,
    [11762] = 3110,
    [11763] = 3110,
    [755] = { 12, classes = WARLOCK }, -- Health Funnel
    [3698] = 755,
    [3699] = 755,
    [3700] = 755,
    [11693] = 755,
    [11694] = 755,
    [11695] = 755,
    [1949] = { 30, classes = WARLOCK }, -- Hellfire
    [11683] = 1949,
    [11684] = 1949,
    [5484] = { 40, classes = WARLOCK }, -- Howl of Terror
    [17928] = 5484,
    [348] = { 1, classes = WARLOCK }, -- Immolate
    [707] = 348,
    [1094] = 348,
    [2941] = 348,
    [11665] = 348,
    [11667] = 348,
    [11668] = 348,
    [25309] = 348,
    [1293812] = { 50, classes = WARLOCK }, -- Incinerate
    [1293813] = 1293812,
    [1122] = { 50, classes = WARLOCK }, -- Inferno
    [427745] = { "pet", classes = WARLOCK }, -- Intercept
    [7814] = { "pet", classes = WARLOCK }, -- Lash of Pain
    [7815] = 7814,
    [7816] = 7814,
    [11778] = 7814,
    [11779] = 7814,
    [11780] = 7814,
    [7870] = { "pet", classes = WARLOCK }, -- Lesser Invisibility
    [1454] = { 6, classes = WARLOCK }, -- Life Tap
    [1455] = 1454,
    [1456] = 1454,
    [11687] = 1454,
    [11688] = 1454,
    [11689] = 1454,
    [19480] = { "pet", classes = WARLOCK }, -- Paranoia
    [4511] = { "pet", classes = WARLOCK }, -- Phase Shift
    [437169] = { 60, classes = WARLOCK }, -- Portal of Summoning
    [5740] = { 20, classes = WARLOCK }, -- Rain of Fire
    [6219] = 5740,
    [11677] = 5740,
    [11678] = 5740,
    [18540] = { 60, classes = WARLOCK }, -- Ritual of Doom
    [698] = { 20, classes = WARLOCK }, -- Ritual of Summoning
    [7812] = { "pet", classes = WARLOCK }, -- Sacrifice
    [19438] = 7812,
    [19440] = 7812,
    [19441] = 7812,
    [19442] = 7812,
    [19443] = 7812,
    [5676] = { 18, classes = WARLOCK }, -- Searing Pain
    [17919] = 5676,
    [17920] = 5676,
    [17921] = 5676,
    [17922] = 5676,
    [17923] = 5676,
    [6358] = { "pet", classes = WARLOCK }, -- Seduction
    [5500] = { 24, classes = WARLOCK }, -- Sense Demons
    [686] = { 1, classes = WARLOCK }, -- Shadow Bolt
    [695] = 686,
    [705] = 686,
    [1088] = 686,
    [1106] = 686,
    [7641] = 686,
    [11659] = 686,
    [11660] = 686,
    [11661] = 686,
    [25307] = 686,
    [6229] = { 32, classes = WARLOCK }, -- Shadow Ward
    [11739] = 6229,
    [11740] = 6229,
    [28610] = 6229,
    [18867] = { 24, classes = WARLOCK }, -- Shadowburn
    [18868] = 18867,
    [18869] = 18867,
    [18870] = 18867,
    [18871] = 18867,
    [18879] = { 38, classes = WARLOCK }, -- Siphon Life
    [18880] = 18879,
    [18881] = 18879,
    [6360] = { "pet", classes = WARLOCK }, -- Soothing Kiss
    [7813] = 6360,
    [11784] = 6360,
    [11785] = 6360,
    [6353] = { 48, classes = WARLOCK }, -- Soul Fire
    [17924] = 6353,
    [19244] = { "pet", classes = WARLOCK }, -- Spell Lock
    [19647] = 19244,
    [1098] = { 30, classes = WARLOCK }, -- Subjugate Demon
    [11725] = 1098,
    [11726] = 1098,
    [17735] = { "pet", classes = WARLOCK }, -- Suffering
    [17750] = 17735,
    [17751] = 17735,
    [17752] = 17735,
    [691] = { 30, classes = WARLOCK }, -- Summon Felhunter
    [713] = { 20, classes = WARLOCK }, -- Summon Incubus
    [712] = { 20, classes = WARLOCK }, -- Summon Succubus
    [697] = { 10, classes = WARLOCK }, -- Summon Voidwalker
    [19478] = { "pet", classes = WARLOCK }, -- Tainted Blood
    [19655] = 19478,
    [19656] = 19478,
    [19660] = 19478,
    [3716] = { "pet", classes = WARLOCK }, -- Torment
    [7809] = 3716,
    [7810] = 3716,
    [7811] = 3716,
    [11774] = 3716,
    [11775] = 3716,
    [5697] = { 16, classes = WARLOCK }, -- Unending Breath
    [6673] = { 1, classes = WARRIOR }, -- Battle Shout
    [5242] = 6673,
    [6192] = 6673,
    [11549] = 6673,
    [11550] = 6673,
    [11551] = 6673,
    [25289] = 6673,
    [18499] = { 32, classes = WARRIOR }, -- Berserker Rage
    [2458] = { 30, classes = WARRIOR }, -- Berserker Stance
    [2687] = { 10, classes = WARRIOR }, -- Bloodrage
    [23892] = { 48, classes = WARRIOR }, -- Bloodthirst
    [23893] = 23892,
    [23894] = 23892,
    [1161] = { 26, classes = WARRIOR }, -- Challenging Shout
    [100] = { 4, classes = WARRIOR }, -- Charge
    [6178] = 100,
    [11578] = 100,
    [845] = { 20, classes = WARRIOR }, -- Cleave
    [7369] = 845,
    [11608] = 845,
    [11609] = 845,
    [20569] = 845,
    [71] = { 10, classes = WARRIOR }, -- Defensive Stance
    [1160] = { 14, classes = WARRIOR }, -- Demoralizing Shout
    [6190] = 1160,
    [11554] = 1160,
    [11555] = 1160,
    [11556] = 1160,
    [676] = { 18, classes = WARRIOR }, -- Disarm
    [5308] = { 24, classes = WARRIOR }, -- Execute
    [20658] = 5308,
    [20660] = 5308,
    [20661] = 5308,
    [20662] = 5308,
    [1715] = { 8, classes = WARRIOR }, -- Hamstring
    [7372] = 1715,
    [7373] = 1715,
    [78] = { 1, classes = WARRIOR }, -- Heroic Strike
    [284] = 78,
    [285] = 78,
    [1608] = 78,
    [11564] = 78,
    [11565] = 78,
    [11566] = 78,
    [11567] = 78,
    [25286] = 78,
    [20252] = { 30, classes = WARRIOR }, -- Intercept
    [20616] = 20252,
    [20617] = 20252,
    [5246] = { 22, classes = WARRIOR }, -- Intimidating Shout
    [694] = { 16, classes = WARRIOR }, -- Mocking Blow
    [7400] = 694,
    [7402] = 694,
    [20559] = 694,
    [20560] = 694,
    [21551] = { 48, classes = WARRIOR }, -- Mortal Strike
    [21552] = 21551,
    [21553] = 21551,
    [7384] = { 12, classes = WARRIOR }, -- Overpower
    [7887] = 7384,
    [11584] = 7384,
    [11585] = 7384,
    [6552] = { 38, classes = WARRIOR }, -- Pummel
    [6554] = 6552,
    [1719] = { 50, classes = WARRIOR }, -- Recklessness
    [772] = { 4, classes = WARRIOR }, -- Rend
    [6546] = 772,
    [6547] = 772,
    [6548] = 772,
    [11572] = 772,
    [11573] = 772,
    [11574] = 772,
    [20230] = { 20, classes = WARRIOR }, -- Retaliation
    [6572] = { 14, classes = WARRIOR }, -- Revenge
    [6574] = 6572,
    [7379] = 6572,
    [11600] = 6572,
    [11601] = 6572,
    [25288] = 6572,
    [72] = { 12, classes = WARRIOR }, -- Shield Bash
    [1671] = 72,
    [1672] = 72,
    [2565] = { 16, classes = WARRIOR }, -- Shield Block
    [23923] = { 48, classes = WARRIOR }, -- Shield Slam
    [23924] = 23923,
    [23925] = 23923,
    [871] = { 28, classes = WARRIOR }, -- Shield Wall
    [1240193] = { 20, classes = WARRIOR }, -- Slam
    [1464] = 1240193,
    [8820] = 1240193,
    [11604] = 1240193,
    [11605] = 1240193,
    [7386] = { 10, classes = WARRIOR }, -- Sunder Armor
    [7405] = 7386,
    [8380] = 7386,
    [11596] = 7386,
    [11597] = 7386,
    [355] = { 10, classes = WARRIOR }, -- Taunt
    [6343] = { 6, classes = WARRIOR }, -- Thunder Clap
    [8198] = 6343,
    [8204] = 6343,
    [8205] = 6343,
    [11580] = 6343,
    [11581] = 6343,
    [461475] = { 2, classes = WARRIOR }, -- Valor of Azeroth
    [402927] = { 20, classes = WARRIOR }, -- Victory Rush
    [1680] = { 36, classes = WARRIOR }, -- Whirlwind
};
